<script setup>
import { nextTick, onBeforeUnmount, onMounted, ref } from 'vue';
import { adminApi } from '@/api';
import { formatPrice } from '@/utils/format';
const items=ref([]), loading=ref(false), error=ref(''), dialog=ref(false), editing=ref(null), trigger=ref(null), dialogRef=ref(null), formError=ref('');
const form=ref({ assetName:'', acquisitionCost:null, salvageValue:0, depreciationStartDate:'', usefulLifeMonths:1 });
async function load(){loading.value=true;error.value='';try{items.value=await adminApi.getFixedAssets()||[]}catch(e){error.value=e.message||'Không thể tải tài sản'}finally{loading.value=false}}
async function open(item,event){trigger.value=event?.currentTarget;editing.value=item||null;formError.value='';form.value=item?{assetName:item.assetName,acquisitionCost:item.acquisitionCost,salvageValue:item.salvageValue,depreciationStartDate:item.depreciationStartDate,usefulLifeMonths:item.usefulLifeMonths}:{assetName:'',acquisitionCost:null,salvageValue:0,depreciationStartDate:new Date().toLocaleDateString('en-CA'),usefulLifeMonths:1};dialog.value=true;document.body.style.overflow='hidden';await nextTick();document.querySelector('#asset-name')?.focus()}
function close(){dialog.value=false;document.body.style.overflow='';nextTick(()=>trigger.value?.focus())}
function handleDialogKeydown(event){if(event.key === 'Escape')return close();if(event.key !== 'Tab')return;const nodes=[...dialogRef.value.querySelectorAll('button:not([disabled]),input:not([disabled])')];if(event.shiftKey&&document.activeElement===nodes[0]){event.preventDefault();nodes.at(-1).focus()}else if(!event.shiftKey&&document.activeElement===nodes.at(-1)){event.preventDefault();nodes[0].focus()}}
async function save(){const payload={...form.value,assetName:form.value.assetName.trim(),acquisitionCost:Number(form.value.acquisitionCost),salvageValue:Number(form.value.salvageValue),usefulLifeMonths:Number(form.value.usefulLifeMonths)};formError.value='';if(payload.salvageValue>=payload.acquisitionCost){formError.value='Giá trị thu hồi phải nhỏ hơn nguyên giá.';return}try{editing.value?await adminApi.updateFixedAsset(editing.value.assetId,payload):await adminApi.createFixedAsset(payload);close();await load()}catch(e){error.value=e.message}}
async function retireFixedAsset(item){if(!confirm(`Ngừng sử dụng tài sản “${item.assetName}”?`))return;try{await adminApi.retireFixedAsset(item.assetId);await load()}catch(e){error.value=e.message}}
onMounted(load);
onBeforeUnmount(()=>{document.body.style.overflow='' });
</script>
<template><main class="finance-page asset-register-workspace"><header><div><p class="eyebrow">Tài chính</p><h1>Tài sản cố định</h1><p>Khấu hao ngày được lấy từ báo cáo máy chủ.</p></div><button class="btn btn-primary" @click="open(null,$event)">Thêm tài sản</button></header><p v-if="error" role="alert" class="error">{{error}}</p><div v-if="loading" role="status" class="panel">Đang tải...</div><div v-else class="panel table-wrapper asset-lifecycle-evidence"><table class="table"><thead><tr><th>Tài sản</th><th>Nguyên giá</th><th>Giá trị thu hồi</th><th>Bắt đầu</th><th>Thời gian</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><tr v-for="item in items" :key="item.assetId"><td>{{item.assetName}}</td><td>{{formatPrice(item.acquisitionCost)}}</td><td>{{formatPrice(item.salvageValue)}}</td><td>{{item.depreciationStartDate}}</td><td>{{item.usefulLifeMonths}} tháng</td><td>{{item.status==='ACTIVE'?'Đang sử dụng':'Đã ngừng'}}</td><td><button v-if="item.status==='ACTIVE'" class="btn btn-outline" @click="open(item,$event)">Sửa</button> <button v-if="item.status==='ACTIVE'" class="btn btn-outline" @click="retireFixedAsset(item)">Ngừng sử dụng</button></td></tr></tbody></table><p v-if="!items.length">Chưa có tài sản cố định.</p></div><div v-if="dialog" class="overlay" @click.self="close"><section ref="dialogRef" role="dialog" aria-modal="true" aria-labelledby="asset-title" class="dialog" @keydown="handleDialogKeydown"><h2 id="asset-title">{{editing?'Sửa tài sản':'Thêm tài sản'}}</h2><form @submit.prevent="save"><label for="asset-name">Tên tài sản<input id="asset-name" v-model="form.assetName" class="form-input" maxlength="255" required></label><label for="acquisition-cost">Nguyên giá<input id="acquisition-cost" v-model.number="form.acquisitionCost" class="form-input" type="number" min="0.01" step="0.01" required></label><label for="salvage-value">Giá trị thu hồi<input id="salvage-value" v-model.number="form.salvageValue" class="form-input" type="number" min="0" step="0.01" required :aria-invalid="!!formError" aria-describedby="asset-error"><span v-if="formError" id="asset-error" class="error" role="alert">{{formError}}</span></label><label for="depreciation-start">Ngày bắt đầu khấu hao<input id="depreciation-start" v-model="form.depreciationStartDate" class="form-input" type="date" required></label><label for="useful-life">Thời gian sử dụng (tháng)<input id="useful-life" v-model.number="form.usefulLifeMonths" class="form-input" type="number" min="1" step="1" required></label><div class="actions"><button type="button" class="btn btn-outline" @click="close">Hủy</button><button class="btn btn-primary">Lưu</button></div></form></section></div></main></template>
<style scoped>.finance-page{display:grid;gap:18px}.finance-page>header{display:flex;justify-content:space-between;align-items:end}.eyebrow{color:var(--role-admin);font-weight:800;text-transform:uppercase}.panel,.dialog{padding:20px;border:1px solid var(--border);border-radius:14px;background:#fff}.table-wrapper{overflow:auto}.error{color:#b91c1c}.overlay{position:fixed;z-index:1000;inset:0;display:grid;place-items:center;background:#0007}.dialog{width:min(520px,calc(100% - 32px))}.dialog form,.dialog label{display:grid;gap:8px}.dialog form{gap:14px}.actions{display:flex;justify-content:end;gap:8px}.btn{min-height:40px}</style>
