<script setup>
import { nextTick, onBeforeUnmount, onMounted, ref } from 'vue';
import { adminApi } from '@/api';
import { formatPrice } from '@/utils/format';

const categories = { RENT: 'Thuê mặt bằng', UTILITIES: 'Điện nước', SALARY: 'Lương', MARKETING: 'Marketing', MAINTENANCE: 'Bảo trì', OTHER: 'Khác' };
const items = ref([]); const loading = ref(false); const error = ref(''); const dialog = ref(false); const editing = ref(null); const trigger = ref(null); const dialogRef = ref(null);
const form = ref({ expenseDate: '', category: 'OTHER', description: '', amount: null });
async function load() { loading.value = true; error.value = ''; try { items.value = await adminApi.getOperatingExpenses() || []; } catch (e) { error.value = e.message || 'Không thể tải chi phí'; } finally { loading.value = false; } }
async function open(item, event) { trigger.value = event?.currentTarget; editing.value = item || null; form.value = item ? { expenseDate: item.expenseDate, category: item.category, description: item.description, amount: item.amount } : { expenseDate: new Date().toLocaleDateString('en-CA'), category: 'OTHER', description: '', amount: null }; dialog.value = true; document.body.style.overflow = 'hidden'; await nextTick(); document.querySelector('#expense-date')?.focus(); }
function close() { dialog.value = false; document.body.style.overflow = ''; nextTick(() => trigger.value?.focus()); }
function handleDialogKeydown(event) { if (event.key === 'Escape') return close(); if (event.key !== 'Tab') return; const nodes = [...dialogRef.value.querySelectorAll('button:not([disabled]),input:not([disabled]),select:not([disabled]),textarea:not([disabled])')]; if (event.shiftKey && document.activeElement === nodes[0]) { event.preventDefault(); nodes.at(-1).focus(); } else if (!event.shiftKey && document.activeElement === nodes.at(-1)) { event.preventDefault(); nodes[0].focus(); } }
async function save() { const payload = { ...form.value, description: form.value.description.trim(), amount: Number(form.value.amount) }; try { editing.value ? await adminApi.updateOperatingExpense(editing.value.expenseId, payload) : await adminApi.createOperatingExpense(payload); close(); await load(); } catch (e) { error.value = e.message; } }
async function remove(item) { if (!confirm(`Xóa chi phí “${item.description}”?`)) return; try { await adminApi.deleteOperatingExpense(item.expenseId); await load(); } catch (e) { error.value = e.message; } }
onMounted(load);
onBeforeUnmount(() => { document.body.style.overflow = ''; });
</script>
<template><main class="finance-page"><header><div><p class="eyebrow">Tài chính</p><h1>Chi phí vận hành</h1></div><button class="btn btn-primary" @click="open(null,$event)">Thêm chi phí</button></header><p v-if="error" role="alert" class="error">{{ error }}</p><div v-if="loading" role="status" class="panel">Đang tải...</div><div v-else class="panel table-wrapper"><table class="table"><thead><tr><th>Ngày</th><th>Loại</th><th>Mô tả</th><th>Số tiền</th><th>Người tạo</th><th>Thao tác</th></tr></thead><tbody><tr v-for="item in items" :key="item.expenseId"><td>{{ item.expenseDate }}</td><td>{{ categories[item.category] }}</td><td>{{ item.description }}</td><td>{{ formatPrice(item.amount) }}</td><td>{{ item.createdByName }}</td><td><button class="btn btn-outline" @click="open(item,$event)">Sửa</button> <button class="btn btn-outline" @click="remove(item)">Xóa</button></td></tr></tbody></table><p v-if="!items.length">Chưa có chi phí vận hành.</p></div><div v-if="dialog" class="overlay" @click.self="close"><section ref="dialogRef" role="dialog" aria-modal="true" aria-labelledby="expense-title" class="dialog" @keydown="handleDialogKeydown"><h2 id="expense-title">{{ editing ? 'Sửa chi phí' : 'Thêm chi phí' }}</h2><form @submit.prevent="save"><label for="expense-date">Ngày<input id="expense-date" v-model="form.expenseDate" class="form-input" type="date" required></label><label for="expense-category">Loại<select id="expense-category" v-model="form.category" class="form-select"><option v-for="(label,key) in categories" :key="key" :value="key">{{ label }}</option></select></label><label for="expense-description">Mô tả<textarea id="expense-description" v-model="form.description" class="form-input" maxlength="500" required></textarea></label><label for="expense-amount">Số tiền<input id="expense-amount" v-model.number="form.amount" class="form-input" type="number" min="0.01" step="0.01" required></label><div class="actions"><button type="button" class="btn btn-outline" @click="close">Hủy</button><button class="btn btn-primary">Lưu</button></div></form></section></div></main></template>
<style scoped>.finance-page{display:grid;gap:18px}.finance-page>header{display:flex;justify-content:space-between;align-items:end}.eyebrow{color:var(--role-admin);font-weight:800;text-transform:uppercase}.panel,.dialog{padding:20px;border:1px solid var(--border);border-radius:14px;background:#fff}.table-wrapper{overflow:auto}.error{color:#b91c1c}.overlay{position:fixed;z-index:1000;inset:0;display:grid;place-items:center;background:#0007}.dialog{width:min(520px,calc(100% - 32px))}.dialog form,.dialog label{display:grid;gap:8px}.dialog form{gap:14px}.actions{display:flex;justify-content:end;gap:8px}.btn{min-height:40px}</style>
