<script setup>
import { computed, onMounted, ref } from 'vue';
import { adminApi } from '@/api';
import { useToast } from '@/stores/toast';
import { buildStockCountPayload, stockCountVariance, validateStockCount } from '@/utils/inventoryOperations';
import { formatQuantity } from '@/utils/inventoryItem';

const toast = useToast();
const counts = ref([]); const inventoryItems = ref([]); const selected = ref(null);
const loading = ref(true); const error = ref(''); const saving = ref(false);
const createForm = ref({ countDate: new Date().toLocaleDateString('en-CA'), frequency: 'DAILY' });
const itemById = computed(() => new Map(inventoryItems.value.map((item) => [item.inventoryItemId, item])));
function item(id) { return itemById.value.get(Number(id)) || {}; }
function money(value) { return Number(value).toLocaleString('vi-VN', { style: 'currency', currency: 'VND', maximumFractionDigits: 0 }); }
function variance(line) { return stockCountVariance(line, item(line.inventoryItemId).averageUnitCost); }
async function load() { loading.value = true; error.value = ''; try { const [list, items] = await Promise.all([adminApi.getStockCounts(), adminApi.getInventoryItems()]); counts.value = Array.isArray(list) ? list : []; inventoryItems.value = Array.isArray(items) ? items : []; } catch (e) { error.value = e.message || 'Không thể tải phiếu kiểm kê'; } finally { loading.value = false; } }
async function create() { saving.value = true; error.value = ''; try { const data = await adminApi.createStockCount(createForm.value); toast.success('Đã tạo phiếu kiểm kê'); await load(); await open(data); } catch (e) { error.value = e.message || 'Không thể tạo phiếu kiểm kê'; } finally { saving.value = false; } }
async function open(count) { error.value = ''; try { const data = await adminApi.getStockCount(count.stockCountId); selected.value = { ...data, items: data.items.map((line) => ({ ...line, actualQuantity: line.actualQuantity == null ? '' : String(line.actualQuantity), reasonCode: line.reasonCode || '', note: line.note || '' })) }; } catch (e) { error.value = e.message || 'Không thể mở phiếu kiểm kê'; } }
async function save() { const validation = validateStockCount(selected.value.items); if (validation.items) { error.value = validation.items; return false; } saving.value = true; error.value = ''; try { selected.value = await adminApi.updateStockCount(selected.value.stockCountId, buildStockCountPayload(selected.value.items)); toast.success('Đã lưu số kiểm thực tế'); await load(); return true; } catch (e) { error.value = e.message || 'Xung đột dữ liệu kiểm kê. Mở lại phiếu và kiểm tra số lý thuyết.'; return false; } finally { saving.value = false; } }
async function approve() { if (!window.confirm(`Duyệt phiếu kiểm kê #${selected.value.stockCountId}? Tồn kho sẽ đổi theo số thực tế.`)) return; if (!(await save())) return; saving.value = true; try { selected.value = await adminApi.approveStockCount(selected.value.stockCountId); toast.success('Đã duyệt kiểm kê'); await load(); } catch (e) { error.value = e.message || 'Không thể duyệt kiểm kê'; } finally { saving.value = false; } }
onMounted(load);
</script>
<template><main class="count-page"><header class="page-heading"><div><p class="eyebrow">Tồn kho</p><h1>Kiểm kê</h1><p>Tạo lịch kiểm, nhập đủ số thực tế, xem chênh lệch trước khi duyệt.</p></div><button class="btn btn-outline" :disabled="loading" @click="load">Làm mới</button></header>
<section class="panel create-panel"><h2>Tạo phiếu kiểm</h2><form @submit.prevent="create"><label>Ngày kiểm<input v-model="createForm.countDate" class="form-input" type="date" required /></label><label>Tần suất<select v-model="createForm.frequency" class="form-select"><option value="DAILY">Hàng ngày</option><option value="WEEKLY">Hàng tuần</option></select></label><button class="btn btn-primary" :disabled="saving">Tạo phiếu</button></form></section>
<p v-if="error" class="error-box" role="alert">{{ error }}</p>
<section class="workspace"><div class="panel list-panel"><h2>Danh sách phiếu</h2><div v-if="loading" class="state" role="status">Đang tải...</div><div v-else-if="!counts.length" class="state">Chưa có phiếu kiểm kê.</div><button v-for="count in counts" :key="count.stockCountId" class="count-row" :class="{active:selected?.stockCountId===count.stockCountId}" @click="open(count)"><span><strong>#{{ count.stockCountId }} · {{ count.countDate }}</strong><small>{{ count.frequency === 'DAILY' ? 'Hàng ngày' : 'Hàng tuần' }} · {{ count.items.length }} mặt hàng</small></span><span class="badge" :class="count.status==='DRAFT'?'badge-warning':'badge-success'">{{ count.status==='DRAFT'?'Nháp':'Đã duyệt' }}</span></button></div>
<section class="panel editor"><div v-if="!selected" class="state">Chọn một phiếu để nhập số kiểm.</div><template v-else><div class="editor-heading"><div><h2>Phiếu #{{ selected.stockCountId }}</h2><p>{{ selected.countDate }} · {{ selected.frequency }}</p></div><span class="badge" :class="selected.status==='DRAFT'?'badge-warning':'badge-success'">{{ selected.status }}</span></div><div v-if="!selected.items.length" class="state">Không có mặt hàng theo tần suất này.</div><form v-else @submit.prevent="save"><div class="table-wrapper"><table class="table"><thead><tr><th>Mặt hàng</th><th>Lý thuyết</th><th>Thực tế</th><th>Chênh lệch</th><th>Lý do</th><th>Ghi chú</th></tr></thead><tbody><tr v-for="line in selected.items" :key="line.inventoryItemId"><td data-label="Mặt hàng"><strong>{{ item(line.inventoryItemId).inventoryCode || `#${line.inventoryItemId}` }}</strong><small>{{ item(line.inventoryItemId).name }}</small></td><td data-label="Lý thuyết">{{ formatQuantity(line.theoreticalQuantity) }}</td><td data-label="Thực tế"><input v-model="line.actualQuantity" class="form-input compact" type="number" min="0" step="0.0001" required :disabled="selected.status!=='DRAFT'" :aria-label="`Số thực tế ${item(line.inventoryItemId).name}`" /></td><td data-label="Chênh lệch"><strong :class="variance(line).quantity<0?'negative':'positive'">{{ formatQuantity(variance(line).quantity) }}</strong><small>{{ money(Math.abs(variance(line).cost)) }}</small></td><td data-label="Lý do"><input v-model="line.reasonCode" class="form-input compact" maxlength="50" :disabled="selected.status!=='DRAFT'" aria-label="Lý do chênh lệch" /></td><td data-label="Ghi chú"><input v-model="line.note" class="form-input compact" maxlength="500" :disabled="selected.status!=='DRAFT'" aria-label="Ghi chú kiểm kê" /></td></tr></tbody></table></div><div v-if="selected.status==='DRAFT'" class="actions"><button class="btn btn-outline" :disabled="saving">Lưu nháp</button><button type="button" class="btn btn-primary" :disabled="saving" @click="approve">Lưu và duyệt</button></div></form></template></section></section></main></template>
<style scoped>.count-page{display:grid;gap:20px}.page-heading,.editor-heading,.actions{display:flex;align-items:center;justify-content:space-between;gap:12px}.page-heading h1{margin:2px 0;font-size:28px}.page-heading p,.editor-heading p{margin:0;color:var(--text-mid)}.eyebrow{color:var(--role-admin)!important;font-size:11px!important;font-weight:800;letter-spacing:.12em;text-transform:uppercase}.panel{background:#fff;border:1px solid var(--border-light);border-radius:14px;padding:20px}.panel h2{margin:0 0 12px;font-size:18px}.create-panel form{display:flex;align-items:end;gap:12px;flex-wrap:wrap}.create-panel label{display:grid;gap:6px;color:var(--text-mid);font-size:12px;font-weight:700}.workspace{display:grid;grid-template-columns:minmax(260px,1fr) minmax(0,3fr);gap:18px;align-items:start}.list-panel{display:grid;gap:8px}.count-row{display:flex;justify-content:space-between;align-items:center;gap:8px;text-align:left;padding:12px;border:1px solid var(--border-light);border-radius:9px;background:#fff}.count-row:hover,.count-row.active{border-color:var(--primary);background:var(--primary-50)}.count-row small,.table small{display:block;color:var(--text-mid);margin-top:3px}.state{text-align:center;padding:32px;color:var(--text-mid)}.error-box{margin:0;color:#b91c1c;background:#fef2f2;padding:10px;border-radius:8px}.table-wrapper{overflow-x:auto}.table{min-width:900px}.compact{min-width:110px}.negative{color:#b91c1c}.positive{color:#047857}.actions{justify-content:flex-end;margin-top:14px}@media(max-width:900px){.workspace{grid-template-columns:1fr}.table-wrapper{overflow:visible}.table thead{display:none}.table,.table tbody,.table tr,.table td{display:block;width:100%}.table tr{padding:14px;border-bottom:1px solid var(--border-light)}.table td{display:grid;grid-template-columns:100px 1fr;gap:10px;padding:6px 0;border:0}.table td:before{content:attr(data-label);color:var(--text-mid);font-size:12px}}@media(max-width:600px){.page-heading{align-items:flex-start;flex-direction:column}.create-panel form,.create-panel label,.create-panel .btn{width:100%}}</style>
