package integration;

import static org.junit.jupiter.api.Assertions.*;
import java.math.BigDecimal;
import java.time.*;
import java.util.*;
import org.junit.jupiter.api.*;
import jakarta.persistence.EntityManager;
import service.*;
import utils.DatabaseUtil;

class StaffPayRateR6IT {
 @Test void disposableEffectiveRateApprovalSnapshotsAndMissingRateRollback(){Assumptions.assumeTrue("true".equalsIgnoreCase(System.getenv("FASTGUY_DISPOSABLE_DB")));EntityManager em=DatabaseUtil.getEntityManager();List<Integer>users=new ArrayList<>(),shifts=new ArrayList<>();try{assertEquals("FastGuyDB_PayRate062_Test",em.createNativeQuery("SELECT DB_NAME()").getSingleResult());int admin=user(em,"ADMIN",users),staff=user(em,"STAFF",users);LocalDate date=LocalDate.of(2092,1,15);int shift=shift(em,staff,date,shifts);StaffPayRateService rates=new StaffPayRateService();rates.create(staff,date.minusDays(10),new BigDecimal("30000.00"),new BigDecimal("45000.00"),admin);Map<String,Object> pending=new WorkShiftService().attendance("2092-01",staff,"PENDING").get(0);Map<String,Object> approved=new WorkShiftService().approveAttendance(shift,admin,Map.of("expectedUpdatedAt",pending.get("updatedAt").toString(),"approvedMinutes",61,"approvedOvertimeMinutes",31));assertEquals("CALCULATED",approved.get("paySnapshotStatus"));assertEquals(new BigDecimal("53750.00"),approved.get("totalPayAmount"));rates.create(staff,date.plusDays(1),new BigDecimal("50000.00"),new BigDecimal("70000.00"),admin);Map<String,Object> stable=new WorkShiftService().attendance("2092-01",staff,"APPROVED").get(0);assertEquals(new BigDecimal("30000.00"),stable.get("regularHourlyRateSnapshot"));int noRateStaff=user(em,"STAFF",users),missing=shift(em,noRateStaff,date.plusDays(1),shifts);Map<String,Object> missingRow=new WorkShiftService().attendance("2092-01",noRateStaff,"PENDING").get(0);assertThrows(StaffPayRateService.MissingRate.class,()->new WorkShiftService().approveAttendance(missing,admin,Map.of("expectedUpdatedAt",missingRow.get("updatedAt").toString(),"approvedMinutes",60,"approvedOvertimeMinutes",0)));assertEquals("PENDING",new WorkShiftService().attendance("2092-01",noRateStaff,"PENDING").get(0).get("attendanceStatus"));}finally{if(em.getTransaction().isActive())em.getTransaction().rollback();em.getTransaction().begin();if(!shifts.isEmpty())em.createNativeQuery("DELETE WorkShift WHERE shift_id IN (:ids)").setParameter("ids",shifts).executeUpdate();if(!users.isEmpty()){em.createNativeQuery("DELETE StaffPayRate WHERE user_id IN (:ids) OR created_by IN (:ids)").setParameter("ids",users).executeUpdate();em.createNativeQuery("DELETE Users WHERE user_id IN (:ids)").setParameter("ids",users).executeUpdate();}em.getTransaction().commit();em.close();DatabaseUtil.close();}}
 private int user(EntityManager em,String role,List<Integer>ids){em.getTransaction().begin();Number id=(Number)em.createNativeQuery("INSERT INTO Users(role_name,email,phone,password_hash,full_name,status,favorite_ids_json,created_at,updated_at) OUTPUT INSERTED.user_id VALUES (:r,:e,:p,'x','R6','ACTIVE',N'[]',SYSDATETIME(),SYSDATETIME())").setParameter("r",role).setParameter("e",role+System.nanoTime()+"@test.local").setParameter("p","9"+Math.abs(System.nanoTime()%1000000000L)).getSingleResult();em.getTransaction().commit();ids.add(id.intValue());return id.intValue();}
 private int shift(EntityManager em,int user,LocalDate date,List<Integer>ids){em.getTransaction().begin();Number id=(Number)em.createNativeQuery("INSERT INTO WorkShift(user_id,shift_date,start_time,end_time,shift_code,staff_role_snapshot,check_in_at,check_out_at,status,attendance_status,created_at,updated_at) OUTPUT INSERTED.shift_id VALUES (:u,:d,'08:00','12:00','MORNING','STAFF',:ci,:co,'CHECKED_OUT','PENDING',SYSDATETIME(),SYSDATETIME())").setParameter("u",user).setParameter("d",date).setParameter("ci",date.atTime(8,0)).setParameter("co",date.atTime(12,31)).getSingleResult();em.getTransaction().commit();ids.add(id.intValue());return id.intValue();}
}
