<script setup>
import PublicContentLayout from '@/components/common/PublicContentLayout.vue';
</script>

<template>
  <PublicContentLayout eyebrow="Pháp lý" title="Chính sách quyền riêng tư" intro="FastGuy tôn trọng quyền riêng tư và chỉ xử lý dữ liệu cần thiết để cung cấp, bảo vệ và cải thiện dịch vụ." updated="02/08/2026">
    <section class="content-section"><h2>1. Dữ liệu chúng tôi thu thập</h2><ul><li>Thông tin tài khoản và liên hệ: họ tên, số điện thoại, email, địa chỉ nhận hàng.</li><li>Thông tin đơn hàng: món đã chọn, giá trị, ghi chú, lịch sử và trạng thái giao hàng.</li><li>Thông tin thanh toán: trạng thái và mã tham chiếu giao dịch; dữ liệu thẻ đầy đủ do đơn vị thanh toán xử lý.</li><li>Dữ liệu kỹ thuật: địa chỉ IP, loại thiết bị, trình duyệt, nhật ký lỗi và hoạt động bảo mật.</li><li>Nội dung bạn chủ động gửi khi đánh giá, liên hệ hoặc yêu cầu hỗ trợ.</li></ul></section>
    <section class="content-section"><h2>2. Mục đích và căn cứ xử lý</h2><p>FastGuy xử lý dữ liệu để tạo và quản lý tài khoản, tiếp nhận đơn, thanh toán, giao hàng, hỗ trợ khách hàng, phòng chống gian lận, bảo đảm an toàn hệ thống và tuân thủ nghĩa vụ pháp lý.</p><p>Khi pháp luật yêu cầu, chúng tôi xin sự đồng ý trước khi gửi nội dung tiếp thị hoặc sử dụng dữ liệu cho mục đích tùy chọn. Bạn có thể rút lại sự đồng ý mà không ảnh hưởng tính hợp pháp của hoạt động xử lý trước đó.</p></section>
    <section class="content-section"><h2>3. Chia sẻ dữ liệu</h2><p>Dữ liệu chỉ được chia sẻ trong phạm vi cần thiết với cửa hàng xử lý món, đối tác giao hàng, nhà cung cấp thanh toán, hạ tầng công nghệ, đơn vị hỗ trợ và cơ quan nhà nước có thẩm quyền. Các bên cung cấp dịch vụ phải bảo mật và chỉ xử lý theo mục đích được giao.</p><p>FastGuy không bán dữ liệu cá nhân của bạn.</p></section>
    <section class="content-section"><h2>4. Cookie và công nghệ tương tự</h2><p>FastGuy có thể dùng cookie thiết yếu để duy trì đăng nhập, giỏ hàng, lựa chọn bảo mật và vận hành trang. Cookie đo lường hoặc tiếp thị, nếu có, chỉ được dùng theo lựa chọn và quy định pháp luật áp dụng. Bạn có thể quản lý cookie trong trình duyệt; tắt cookie thiết yếu có thể làm một số chức năng không hoạt động.</p></section>
    <section class="content-section"><h2>5. Lưu trữ và bảo mật</h2><p>Dữ liệu được giữ trong thời gian cần thiết cho mục đích nêu trên, giải quyết tranh chấp và đáp ứng thời hạn lưu trữ theo pháp luật. Sau đó dữ liệu được xóa hoặc ẩn danh an toàn.</p><p>FastGuy áp dụng kiểm soát truy cập, mã hóa phù hợp, giám sát và quy trình ứng phó sự cố. Không hệ thống nào an toàn tuyệt đối; nếu phát hiện sự cố ảnh hưởng quyền lợi của bạn, chúng tôi sẽ xử lý và thông báo theo quy định.</p></section>
    <section class="content-section"><h2>6. Quyền của bạn</h2><p>Tùy quy định áp dụng, bạn có thể yêu cầu biết, truy cập, chỉnh sửa, hạn chế xử lý, rút lại sự đồng ý hoặc xóa dữ liệu cá nhân. Một số dữ liệu vẫn cần được lưu để hoàn thành hợp đồng, bảo vệ quyền lợi hợp pháp hoặc tuân thủ pháp luật.</p><p>Để bảo vệ tài khoản, FastGuy có thể yêu cầu xác minh danh tính trước khi xử lý yêu cầu.</p></section>
    <section class="content-section"><h2>7. Dữ liệu trẻ em</h2><p>Dịch vụ không chủ đích thu thập dữ liệu của trẻ em không đủ tuổi tự mình đồng ý theo pháp luật. Người đại diện hợp pháp có thể yêu cầu kiểm tra và xóa dữ liệu đã cung cấp không phù hợp.</p></section>
    <section class="content-section"><h2>8. Cập nhật và liên hệ</h2><p>Chính sách có thể được cập nhật khi dịch vụ hoặc quy định thay đổi. Phiên bản mới và ngày cập nhật được công bố tại trang này; thay đổi quan trọng sẽ được thông báo bằng phương thức phù hợp.</p><p>Muốn thực hiện quyền riêng tư hoặc phản ánh vấn đề dữ liệu, vui lòng truy cập <RouterLink to="/help">Trung tâm trợ giúp</RouterLink> và gửi yêu cầu qua tài khoản. Hãy nêu rõ nội dung yêu cầu và thông tin cần thiết để xác minh.</p></section>
  </PublicContentLayout>
</template>
