<script setup>
import PublicContentLayout from '@/components/common/PublicContentLayout.vue';
</script>

<template>
  <PublicContentLayout eyebrow="Pháp lý" title="Điều khoản sử dụng" intro="Điều khoản điều chỉnh việc truy cập và sử dụng nền tảng đặt món FastGuy." updated="02/08/2026">
    <section class="content-section"><h2>1. Phạm vi và chấp thuận</h2><p>Khi truy cập, tạo tài khoản hoặc đặt hàng qua FastGuy, bạn xác nhận đã đọc và đồng ý với các điều khoản này. Nếu không đồng ý, vui lòng ngừng sử dụng dịch vụ.</p></section>
    <section class="content-section"><h2>2. Tài khoản người dùng</h2><p>Bạn phải cung cấp thông tin chính xác, cập nhật và bảo mật thông tin đăng nhập. Bạn chịu trách nhiệm cho hoạt động phát sinh từ tài khoản của mình và cần thông báo cho FastGuy khi nghi ngờ truy cập trái phép.</p><p>Người dùng phải đủ năng lực thực hiện giao dịch theo pháp luật Việt Nam. Người chưa thành niên cần có sự đồng ý của người đại diện hợp pháp.</p></section>
    <section class="content-section"><h2>3. Đặt hàng và giá</h2><p>Thông tin món ăn, giá, phí giao hàng, ưu đãi và tổng thanh toán được hiển thị trước khi xác nhận. Đơn hàng chỉ được chấp nhận khi FastGuy gửi xác nhận. FastGuy có thể từ chối hoặc hủy đơn do hết món, ngoài vùng phục vụ, lỗi giá rõ ràng, nghi ngờ gian lận hoặc sự kiện bất khả kháng; khoản đã thu sẽ được xử lý hoàn theo quy định.</p></section>
    <section class="content-section"><h2>4. Thanh toán</h2><p>Bạn đồng ý thanh toán đầy đủ bằng phương thức đã chọn. Giao dịch trực tuyến có thể chịu điều khoản của ngân hàng hoặc đơn vị trung gian thanh toán. FastGuy không yêu cầu bạn cung cấp mật khẩu, mã PIN hoặc mã OTP qua cuộc gọi hay tin nhắn.</p></section>
    <section class="content-section"><h2>5. Giao hàng, thay đổi và hủy đơn</h2><p>Thời gian giao chỉ là dự kiến và có thể thay đổi vì giao thông, thời tiết hoặc lượng đơn. Bạn cần cung cấp địa chỉ, số điện thoại chính xác và phối hợp nhận hàng.</p><p>Yêu cầu sửa hoặc hủy được xem xét trước khi món bắt đầu chuẩn bị. Đơn đã chế biến hoặc đang giao có thể không được hủy. Việc hoàn tiền căn cứ trạng thái đơn, nguyên nhân và phương thức thanh toán.</p></section>
    <section class="content-section"><h2>6. Hành vi không được phép</h2><ul><li>Sử dụng dịch vụ cho mục đích gian lận, trái pháp luật hoặc xâm phạm quyền của người khác.</li><li>Can thiệp hệ thống, thu thập dữ liệu tự động trái phép hoặc phát tán mã độc.</li><li>Lạm dụng ưu đãi, tạo đơn giả, quấy rối nhân viên, đối tác giao hàng hoặc người dùng khác.</li></ul></section>
    <section class="content-section"><h2>7. Trách nhiệm và khiếu nại</h2><p>FastGuy cung cấp dịch vụ trong phạm vi pháp luật cho phép và chịu trách nhiệm đối với thiệt hại trực tiếp do lỗi của mình. Không bên nào chịu trách nhiệm cho việc không thực hiện nghĩa vụ do sự kiện nằm ngoài khả năng kiểm soát hợp lý.</p><p>Khiếu nại nên kèm mã đơn, mô tả và bằng chứng liên quan. FastGuy sẽ xác minh, phản hồi trong thời gian hợp lý và ưu tiên giải quyết bằng thương lượng.</p></section>
    <section class="content-section"><h2>8. Sở hữu trí tuệ và thay đổi điều khoản</h2><p>Nhãn hiệu, giao diện và nội dung thuộc FastGuy hoặc bên cấp phép, trừ khi có ghi chú khác. Bạn không được sao chép hoặc khai thác thương mại khi chưa được phép.</p><p>FastGuy có thể cập nhật điều khoản để phản ánh thay đổi dịch vụ hoặc pháp luật. Phiên bản mới được công bố trên trang này cùng ngày hiệu lực. Việc tiếp tục sử dụng sau ngày hiệu lực được xem là chấp thuận nội dung cập nhật.</p></section>
    <section class="content-section"><h2>9. Luật áp dụng và liên hệ</h2><p>Điều khoản được điều chỉnh bởi pháp luật Việt Nam. Tranh chấp không thể giải quyết bằng thương lượng sẽ được đưa ra cơ quan có thẩm quyền tại Việt Nam.</p><p>Thông tin hướng dẫn về đơn hàng và điều khoản được đăng tại <RouterLink to="/help">Trung tâm trợ giúp</RouterLink>.</p></section>
  </PublicContentLayout>
</template>
