package service;

import java.math.BigDecimal;
import java.math.MathContext;
import java.math.RoundingMode;
import java.time.Instant;
import java.time.LocalDateTime;
import java.util.*;
import java.util.function.Supplier;
import entity.*;
import jakarta.persistence.EntityManager;
import jakarta.persistence.LockModeType;
import utils.DatabaseUtil;

public class AdminRecipeService {
    private static final Set<String> MODES=Set.of("INGREDIENT","FINISHED_GOOD","UNTRACKED","SUSPENDED");
    public static final String INGREDIENT_NOT_READY="Chưa thể bật quản lý theo công thức: cần công thức đang hoạt động, có ít nhất một nguyên liệu đang hoạt động.";
    public static final String INGREDIENT_RECIPE_ACTIVE_REQUIRED="Không thể ngừng công thức khi kích cỡ đang quản lý tồn theo công thức. Hãy đổi cách quản lý tồn trước.";
    public static final String FINISHED_GOOD_NOT_READY="Chưa thể bật quản lý thành phẩm: cần một mặt hàng kho thành phẩm đang hoạt động được liên kết với kích cỡ này.";
    private final Supplier<EntityManager> entityManagers;
    private final InventoryAvailabilityService availability;
    public AdminRecipeService(){this(DatabaseUtil::getEntityManager,new InventoryAvailabilityService());}
    AdminRecipeService(Supplier<EntityManager> managers){this(managers,new InventoryAvailabilityService());}
    AdminRecipeService(Supplier<EntityManager> managers,InventoryAvailabilityService availability){this.entityManagers=managers;this.availability=availability;}
    public Map<String,Object> get(int variantId){EntityManager em=entityManagers.get();try{Recipe r=find(em,variantId);if(r==null)throw new NoSuchElementException("Recipe not found");return dto(r);}finally{em.close();}}
    public Map<String,Object> replace(int variantId,BigDecimal yield,boolean active,List<Integer> ids,List<BigDecimal> quantities){validateItems(ids,quantities);AdminInventoryService.decimal(yield,true);EntityManager em=entityManagers.get();try{em.getTransaction().begin();ProductVariant v=em.find(ProductVariant.class,variantId,jakarta.persistence.LockModeType.PESSIMISTIC_WRITE);if(v==null)throw new NoSuchElementException("Variant not found");if("INGREDIENT".equals(v.getInventoryMode())&&!active)throw new ModeNotReadyException(INGREDIENT_RECIPE_ACTIVE_REQUIRED);List<Recipe> recipes=em.createQuery("SELECT r FROM Recipe r WHERE r.variant.variantId=:id",Recipe.class).setParameter("id",variantId).setLockMode(LockModeType.PESSIMISTIC_WRITE).getResultList();Recipe r=recipes.isEmpty()?null:recipes.get(0);Map<Integer,InventoryItem> items=new HashMap<>();for(int itemId:ids.stream().sorted().toList()){InventoryItem item=em.find(InventoryItem.class,itemId,LockModeType.PESSIMISTIC_WRITE);requireRecipeIngredient(item);items.put(itemId,item);}if(r==null){r=new Recipe();r.setVariant(v);em.persist(r);}else em.createQuery("DELETE FROM RecipeItem i WHERE i.recipe=:recipe").setParameter("recipe",r).executeUpdate();r.setYieldQuantity(yield);r.setActive(active);List<RecipeItem> lines=new ArrayList<>();for(int x=0;x<ids.size();x++){RecipeItem line=new RecipeItem();line.setRecipe(r);line.setInventoryItem(items.get(ids.get(x)));line.setQuantity(quantities.get(x));em.persist(line);lines.add(line);}r.setItems(lines);em.flush();em.getTransaction().commit();return dto(r);}catch(RuntimeException e){if(em.getTransaction().isActive())em.getTransaction().rollback();throw e;}finally{em.close();}}
    public Map<String,Object> settings(int variantId){EntityManager em=entityManagers.get();try{ProductVariant v=em.find(ProductVariant.class,variantId);if(v==null)throw new NoSuchElementException("Variant not found");return settingsDto(v);}finally{em.close();}}
    public Map<String,Object> updateSettings(int variantId,String mode){validateMode(mode,true);EntityManager em=entityManagers.get();try{em.getTransaction().begin();ProductVariant v=em.find(ProductVariant.class,variantId,LockModeType.PESSIMISTIC_WRITE);if(v==null)throw new NoSuchElementException("Variant not found");List<Recipe> recipes=em.createQuery("SELECT r FROM Recipe r WHERE r.variant.variantId=:id",Recipe.class).setParameter("id",variantId).setLockMode(LockModeType.PESSIMISTIC_READ).getResultList();Recipe recipe=recipes.isEmpty()?null:recipes.get(0);List<RecipeItem> recipeItems=recipe==null?List.of():em.createQuery("SELECT ri FROM RecipeItem ri WHERE ri.recipe=:recipe ORDER BY ri.inventoryItem.inventoryItemId",RecipeItem.class).setParameter("recipe",recipe).setLockMode(LockModeType.PESSIMISTIC_READ).getResultList();boolean recipeReady=recipe!=null&&recipe.isActive()&&recipe.getYieldQuantity()!=null&&recipe.getYieldQuantity().signum()>0&&!recipeItems.isEmpty();for(RecipeItem line:recipeItems){int itemId=line.getInventoryItem().getInventoryItemId();InventoryItem item=em.find(InventoryItem.class,itemId,LockModeType.PESSIMISTIC_READ);recipeReady&=line.getQuantity()!=null&&line.getQuantity().signum()>0&&item.isActive()&&"INGREDIENT".equals(item.getItemType());}List<VariantInventoryItem> mappings=em.createQuery("SELECT m FROM VariantInventoryItem m WHERE m.variant.variantId=:id ORDER BY m.inventoryItem.inventoryItemId",VariantInventoryItem.class).setParameter("id",variantId).setLockMode(LockModeType.PESSIMISTIC_READ).getResultList();List<InventoryItem> finishedItems=new ArrayList<>();for(VariantInventoryItem mapping:mappings){int itemId=mapping.getInventoryItem().getInventoryItemId();finishedItems.add(em.find(InventoryItem.class,itemId,LockModeType.PESSIMISTIC_READ));}boolean finishedGoodReady=finishedItems.size()==1&&finishedItems.get(0).isActive()&&"FINISHED_GOOD".equals(finishedItems.get(0).getItemType());requireModeReady(mode,recipeReady,finishedGoodReady);v.setInventoryMode(mode);em.getTransaction().commit();return settingsDto(v);}catch(RuntimeException e){if(em.getTransaction().isActive())em.getTransaction().rollback();throw e;}finally{em.close();}}
    public Map<String,Object> replace(int variantId,BigDecimal yield,boolean active,List<Integer> ids,List<BigDecimal> quantities,LocalDateTime expected){
        validateItems(ids,quantities);AdminInventoryService.decimal(yield,true);EntityManager em=entityManagers.get();
        try{em.getTransaction().begin();ProductVariant v=em.find(ProductVariant.class,variantId,LockModeType.PESSIMISTIC_WRITE);if(v==null)throw new NoSuchElementException("Variant not found");if("INGREDIENT".equals(v.getInventoryMode())&&!active)throw new ModeNotReadyException(INGREDIENT_RECIPE_ACTIVE_REQUIRED);List<Recipe> recipes=em.createQuery("SELECT r FROM Recipe r WHERE r.variant.variantId=:id",Recipe.class).setParameter("id",variantId).setLockMode(LockModeType.PESSIMISTIC_WRITE).getResultList();Recipe r=recipes.isEmpty()?null:recipes.get(0);requireExpectedVersion(r==null?null:r.getUpdatedAt(),expected);Map<Integer,InventoryItem> items=new HashMap<>();for(int itemId:ids.stream().sorted().toList()){InventoryItem item=em.find(InventoryItem.class,itemId,LockModeType.PESSIMISTIC_WRITE);requireRecipeIngredient(item);items.put(itemId,item);}if(r==null){r=new Recipe();r.setVariant(v);em.persist(r);}else{em.createQuery("DELETE FROM RecipeItem i WHERE i.recipe=:recipe").setParameter("recipe",r).executeUpdate();r.advanceUpdatedAt();}r.setYieldQuantity(yield);r.setActive(active);List<RecipeItem> lines=new ArrayList<>();for(int x=0;x<ids.size();x++){RecipeItem line=new RecipeItem();line.setRecipe(r);line.setInventoryItem(items.get(ids.get(x)));line.setQuantity(quantities.get(x));em.persist(line);lines.add(line);}r.setItems(lines);em.flush();Map<String,Object>result=dto(r);em.getTransaction().commit();return result;}catch(RuntimeException e){if(em.getTransaction().isActive())em.getTransaction().rollback();throw e;}finally{em.close();}
    }
    public Map<String,Object> updateSettings(int variantId,String mode,LocalDateTime expected){
        validateMode(mode,true);EntityManager em=entityManagers.get();
        try{em.getTransaction().begin();ProductVariant v=em.find(ProductVariant.class,variantId,LockModeType.PESSIMISTIC_WRITE);if(v==null)throw new NoSuchElementException("Variant not found");requireExpectedVersion(v.getUpdatedAt(),expected);List<Recipe> recipes=em.createQuery("SELECT r FROM Recipe r WHERE r.variant.variantId=:id",Recipe.class).setParameter("id",variantId).setLockMode(LockModeType.PESSIMISTIC_READ).getResultList();Recipe recipe=recipes.isEmpty()?null:recipes.get(0);List<RecipeItem> recipeItems=recipe==null?List.of():em.createQuery("SELECT ri FROM RecipeItem ri WHERE ri.recipe=:recipe ORDER BY ri.inventoryItem.inventoryItemId",RecipeItem.class).setParameter("recipe",recipe).setLockMode(LockModeType.PESSIMISTIC_READ).getResultList();boolean recipeReady=recipe!=null&&recipe.isActive()&&recipe.getYieldQuantity()!=null&&recipe.getYieldQuantity().signum()>0&&!recipeItems.isEmpty();for(RecipeItem line:recipeItems){InventoryItem item=em.find(InventoryItem.class,line.getInventoryItem().getInventoryItemId(),LockModeType.PESSIMISTIC_READ);recipeReady&=line.getQuantity()!=null&&line.getQuantity().signum()>0&&item.isActive()&&"INGREDIENT".equals(item.getItemType());}List<VariantInventoryItem> mappings=em.createQuery("SELECT m FROM VariantInventoryItem m WHERE m.variant.variantId=:id ORDER BY m.inventoryItem.inventoryItemId",VariantInventoryItem.class).setParameter("id",variantId).setLockMode(LockModeType.PESSIMISTIC_READ).getResultList();List<InventoryItem> finishedItems=new ArrayList<>();for(VariantInventoryItem mapping:mappings)finishedItems.add(em.find(InventoryItem.class,mapping.getInventoryItem().getInventoryItemId(),LockModeType.PESSIMISTIC_READ));requireModeReady(mode,recipeReady,finishedItems.size()==1&&finishedItems.get(0).isActive()&&"FINISHED_GOOD".equals(finishedItems.get(0).getItemType()));v.setInventoryMode(mode);v.advanceUpdatedAt();em.flush();Map<String,Object>result=settingsDto(v);em.getTransaction().commit();return result;}catch(RuntimeException e){if(em.getTransaction().isActive())em.getTransaction().rollback();throw e;}finally{em.close();}
    }
    public Map<String,Object> capacity(int variantId){EntityManager em=entityManagers.get();try{em.getTransaction().begin();CapacityStock stock=loadCapacity(em,variantId);Map<String,Object> result=calculateCapacity(stock,Instant.now());em.getTransaction().commit();return result;}catch(RuntimeException e){if(em.getTransaction().isActive())em.getTransaction().rollback();throw e;}finally{em.close();}}
    public Map<String,Object> availability(int variantId){EntityManager em=entityManagers.get();try{var a=availability.availability(em,variantId);Map<String,Object>m=new LinkedHashMap<>();m.put("availabilityStatus",switch(a.status()){case "AVAILABLE"->a.mode().equals("UNTRACKED")?"UNTRACKED":"IN_STOCK";case "UNAVAILABLE"->"OUT_OF_STOCK";default->a.status();});if(a.servings()!=null&&a.servings()>0)m.put("remainingServings",Math.min(3,a.servings()));return m;}finally{em.close();}}
    public static void validateItems(List<Integer> ids,List<BigDecimal> quantities){if(ids==null||quantities==null||ids.isEmpty()||ids.size()!=quantities.size()||new HashSet<>(ids).size()!=ids.size())throw new IllegalArgumentException("Invalid recipe items");for(int i=0;i<ids.size();i++)if(ids.get(i)==null||ids.get(i)<=0)throw new IllegalArgumentException("Invalid recipe item");else AdminInventoryService.decimal(quantities.get(i),true);}
    static void requireRecipeIngredient(InventoryItem item){if(item==null||!item.isActive()||!"INGREDIENT".equals(item.getItemType()))throw new IllegalArgumentException("All recipe items must be active ingredients");}
    public static void validateMode(String mode,boolean validRecipe){if(!MODES.contains(mode))throw new IllegalArgumentException("Invalid inventoryMode");if(mode.equals("INGREDIENT")&&!validRecipe)throw new IllegalArgumentException("INGREDIENT mode requires an active recipe");}
    public static void requireModeReady(String mode,boolean recipeReady,boolean finishedGoodReady){validateMode(mode,true);if("INGREDIENT".equals(mode)&&!recipeReady)throw new ModeNotReadyException(INGREDIENT_NOT_READY);if("FINISHED_GOOD".equals(mode)&&!finishedGoodReady)throw new ModeNotReadyException(FINISHED_GOOD_NOT_READY);}
    public static class ModeNotReadyException extends IllegalStateException{public ModeNotReadyException(String message){super(message);}}
    public static class OptimisticConflictException extends IllegalStateException{public OptimisticConflictException(){super("Dữ liệu đã thay đổi. Tải lại dữ liệu mới trước khi lưu.");}}
    static void requireExpectedVersion(LocalDateTime current,LocalDateTime expected){if(!Objects.equals(current,expected))throw new OptimisticConflictException();}
    private Recipe find(EntityManager em,int id){List<Recipe>r=em.createQuery("SELECT DISTINCT r FROM Recipe r LEFT JOIN FETCH r.items i LEFT JOIN FETCH i.inventoryItem WHERE r.variant.variantId=:id",Recipe.class).setParameter("id",id).getResultList();return r.isEmpty()?null:r.get(0);}
    private static Map<String,Object> dto(Recipe r){Map<String,Object>m=new LinkedHashMap<>();m.put("recipeId",r.getRecipeId());m.put("variantId",r.getVariant().getVariantId());m.put("yieldQuantity",r.getYieldQuantity());m.put("active",r.isActive());m.put("items",r.getItems().stream().map(i->Map.of("inventoryItemId",i.getInventoryItem().getInventoryItemId(),"quantity",i.getQuantity())).toList());m.put("createdAt",r.getCreatedAt());m.put("updatedAt",r.getUpdatedAt());return m;}
    private static Map<String,Object> settingsDto(ProductVariant v){Map<String,Object>m=new LinkedHashMap<>();m.put("variantId",v.getVariantId());m.put("inventoryMode",v.getInventoryMode());m.put("updatedAt",v.getUpdatedAt());return m;}

    public record CapacityItem(int inventoryItemId,String name,String baseUnit,BigDecimal onHandQuantity,BigDecimal reservedQuantity,BigDecimal quantity,BigDecimal averageUnitCost,boolean active){}
    public record CapacityStock(int variantId,String inventoryMode,BigDecimal variantPrice,BigDecimal yieldQuantity,boolean valid,List<CapacityItem> items){}

    public static Map<String,Object> calculateCapacity(CapacityStock stock,Instant calculatedAt){
        Map<String,Object> result=new LinkedHashMap<>();result.put("variantId",stock.variantId());result.put("inventoryMode",stock.inventoryMode());
        result.put("calculatedAt",calculatedAt);result.put("variantPrice",stock.variantPrice());
        if("UNTRACKED".equals(stock.inventoryMode())){result.put("availableServings",null);result.put("limitingInventoryItemId",null);result.put("ingredients",List.of());cost(result,"NOT_APPLICABLE",null,null,List.of());return result;}
        if(!stock.valid()||stock.items().isEmpty()){result.put("availableServings",0);result.put("limitingInventoryItemId",null);result.put("ingredients",List.of());cost(result,"NOT_APPLICABLE",null,null,List.of());return result;}
        List<Line> lines=stock.items().stream().map(i->line(i,"FINISHED_GOOD".equals(stock.inventoryMode())?BigDecimal.ONE:i.quantity().divide(stock.yieldQuantity(),MathContext.DECIMAL128))).sorted(Comparator.comparingInt(x->x.item().inventoryItemId())).toList();
        Line limiting=lines.stream().min(Comparator.comparingInt(Line::servings).thenComparingInt(x->x.item().inventoryItemId())).orElseThrow();
        boolean suspended="SUSPENDED".equals(stock.inventoryMode());result.put("availableServings",suspended?0:limiting.servings());result.put("limitingInventoryItemId",suspended?null:limiting.item().inventoryItemId());
        List<Map<String,Object>> ingredients=new ArrayList<>();List<Map<String,Object>> missing=new ArrayList<>();BigDecimal total=BigDecimal.ZERO;
        for(Line line:lines){CapacityItem i=line.item();boolean costAvailable=i.averageUnitCost()!=null&&i.averageUnitCost().signum()>0;BigDecimal lineCost=costAvailable?line.required().multiply(i.averageUnitCost()).setScale(4,RoundingMode.HALF_UP):null;if(costAvailable)total=total.add(lineCost);else missing.add(Map.of("inventoryItemId",i.inventoryItemId(),"name",i.name()));Map<String,Object> m=new LinkedHashMap<>();m.put("inventoryItemId",i.inventoryItemId());m.put("name",i.name());m.put("baseUnit",i.baseUnit());m.put("onHandQuantity",i.onHandQuantity());m.put("reservedQuantity",i.reservedQuantity());m.put("availableQuantity",i.onHandQuantity().subtract(i.reservedQuantity()));m.put("requiredPerServing",line.required());m.put("availableServings",line.servings());m.put("averageUnitCost",i.averageUnitCost());m.put("costPerServing",lineCost);m.put("costAvailable",costAvailable);m.put("limiting",!suspended&&i.inventoryItemId()==limiting.item().inventoryItemId());m.put("active",i.active());ingredients.add(m);}
        result.put("ingredients",ingredients);if(missing.isEmpty()){BigDecimal recipeCost=total.setScale(4,RoundingMode.HALF_UP);BigDecimal percent=stock.variantPrice().signum()>0?recipeCost.multiply(BigDecimal.valueOf(100)).divide(stock.variantPrice(),4,RoundingMode.HALF_UP):null;cost(result,"COMPLETE",recipeCost,percent,missing);}else cost(result,"INCOMPLETE",null,null,missing);return result;
    }
    private static Line line(CapacityItem item,BigDecimal required){BigDecimal available=item.onHandQuantity().subtract(item.reservedQuantity());BigDecimal servings=available.divide(required,0,RoundingMode.FLOOR);int count=servings.compareTo(BigDecimal.valueOf(Integer.MAX_VALUE))>0?Integer.MAX_VALUE:servings.intValue();return new Line(item,required,count);}
    private static void cost(Map<String,Object> result,String status,BigDecimal recipeCost,BigDecimal percent,List<Map<String,Object>> missing){result.put("costStatus",status);result.put("recipeCostPerServing",recipeCost);result.put("foodCostPercent",percent);result.put("missingCostItemCount",missing.size());result.put("missingCostItems",missing);}
    private record Line(CapacityItem item,BigDecimal required,int servings){}

    private CapacityStock loadCapacity(EntityManager em,int variantId){ProductVariant v=em.find(ProductVariant.class,variantId,LockModeType.PESSIMISTIC_READ);if(v==null)throw new NoSuchElementException("Variant not found");String mode=v.getInventoryMode();if(!MODES.contains(mode))throw new IllegalStateException("Unknown persisted inventory mode");if("UNTRACKED".equals(mode))return new CapacityStock(variantId,mode,v.getPrice(),BigDecimal.ONE,true,List.of());List<CapacityItem> items=new ArrayList<>();BigDecimal yield=BigDecimal.ONE;boolean valid=false;
        if("INGREDIENT".equals(mode)||"SUSPENDED".equals(mode)){List<Recipe> recipes=em.createQuery("SELECT r FROM Recipe r WHERE r.variant.variantId=:id",Recipe.class).setParameter("id",variantId).setLockMode(LockModeType.PESSIMISTIC_READ).getResultList();Recipe r=recipes.isEmpty()?null:recipes.get(0);if(r!=null&&r.isActive()&&r.getYieldQuantity()!=null&&r.getYieldQuantity().signum()>0){yield=r.getYieldQuantity();List<RecipeItem> lines=em.createQuery("SELECT ri FROM RecipeItem ri WHERE ri.recipe=:recipe ORDER BY ri.inventoryItem.inventoryItemId",RecipeItem.class).setParameter("recipe",r).setLockMode(LockModeType.PESSIMISTIC_READ).getResultList();boolean ingredients=true;for(RecipeItem line:lines){int itemId=line.getInventoryItem().getInventoryItemId();InventoryItem item=em.find(InventoryItem.class,itemId,LockModeType.PESSIMISTIC_READ);ingredients&="INGREDIENT".equals(item.getItemType());items.add(capacityItem(item,line.getQuantity()));}valid=ingredients&&!items.isEmpty()&&items.stream().allMatch(i->i.active()&&i.quantity()!=null&&i.quantity().signum()>0);}}
        if(("FINISHED_GOOD".equals(mode)||"SUSPENDED".equals(mode)&&!valid)){List<VariantInventoryItem> mappings=em.createQuery("SELECT m FROM VariantInventoryItem m WHERE m.variant.variantId=:id ORDER BY m.inventoryItem.inventoryItemId",VariantInventoryItem.class).setParameter("id",variantId).setLockMode(LockModeType.PESSIMISTIC_READ).getResultList();items=new ArrayList<>();boolean finishedGood=true;for(VariantInventoryItem mapping:mappings){int itemId=mapping.getInventoryItem().getInventoryItemId();InventoryItem item=em.find(InventoryItem.class,itemId,LockModeType.PESSIMISTIC_READ);finishedGood&="FINISHED_GOOD".equals(item.getItemType());items.add(capacityItem(item,BigDecimal.ONE));}yield=BigDecimal.ONE;valid=items.size()==1&&items.get(0).active()&&finishedGood;}
        return new CapacityStock(variantId,mode,v.getPrice(),yield,valid,items);}
    private static CapacityItem capacityItem(InventoryItem i,BigDecimal quantity){return new CapacityItem(i.getInventoryItemId(),i.getName(),i.getBaseUnit(),i.getOnHandQuantity(),i.getReservedQuantity(),quantity,i.getAverageUnitCost(),i.isActive());}
}
