package service;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.*;
import java.util.function.Supplier;

import entity.*;
import exception.InventoryItemConflictException;
import jakarta.persistence.EntityManager;
import utils.DatabaseUtil;

public class AdminInventoryService {
    private static final BigDecimal MAX = new BigDecimal("999999999999999.9999");
    private static final Set<String> UNITS = Set.of("G", "ML", "PIECE");
    private static final Set<String> TYPES = Set.of("INGREDIENT", "FINISHED_GOOD");
    private final Supplier<EntityManager> entityManagers;
    public AdminInventoryService() { this(DatabaseUtil::getEntityManager); }
    AdminInventoryService(Supplier<EntityManager> entityManagers) { this.entityManagers = entityManagers; }

    public List<Map<String,Object>> list() { EntityManager em=entityManagers.get(); try { return em.createQuery("SELECT i FROM InventoryItem i ORDER BY i.inventoryItemId", InventoryItem.class).getResultList().stream().map(AdminInventoryService::dto).toList(); } finally { em.close(); } }
    public Map<String,Object> get(int id) { EntityManager em=entityManagers.get(); try { InventoryItem i=em.find(InventoryItem.class,id); if(i==null) throw new NoSuchElementException("Inventory item not found"); return dto(i); } finally { em.close(); } }
    public Map<String,Object> create(String name,String type,String unit,BigDecimal minimum,boolean active) { return create("INV-"+UUID.randomUUID().toString().substring(0,8).toUpperCase(Locale.ROOT),name,type,unit,minimum,"WEEKLY",active); }
    public Map<String,Object> create(String code,String name,String type,String unit,BigDecimal minimum,String frequency,boolean active) { validate(code,name,type,unit,minimum,frequency); EntityManager em=entityManagers.get(); try { em.getTransaction().begin(); InventoryItem i=new InventoryItem(); apply(i,code,name,type,unit,minimum,frequency,active); em.persist(i); em.flush(); em.getTransaction().commit(); return dto(i); } catch(RuntimeException e){ if(em.getTransaction().isActive())em.getTransaction().rollback(); throw e;} finally{em.close();} }
    public Map<String,Object> update(int id,String name,String type,String unit,BigDecimal minimum,boolean active) { EntityManager em=entityManagers.get();try{InventoryItem i=em.find(InventoryItem.class,id);if(i==null)throw new NoSuchElementException("Inventory item not found");return update(id,i.getInventoryCode(),name,type,unit,minimum,i.getCountFrequency(),active);}finally{em.close();} }
    public Map<String,Object> update(int id,String code,String name,String type,String unit,BigDecimal minimum,String frequency,boolean active) { validate(code,name,type,unit,minimum,frequency); EntityManager em=entityManagers.get(); try { em.getTransaction().begin(); boolean mapped=!em.createQuery("SELECT m FROM VariantInventoryItem m WHERE m.inventoryItem.inventoryItemId=:id ORDER BY m.variantInventoryItemId",VariantInventoryItem.class).setParameter("id",id).setLockMode(jakarta.persistence.LockModeType.PESSIMISTIC_WRITE).getResultList().isEmpty(); InventoryItem i=em.find(InventoryItem.class,id,jakarta.persistence.LockModeType.PESSIMISTIC_WRITE); if(i==null)throw new NoSuchElementException("Inventory item not found"); boolean recipeReferenced=!em.createQuery("SELECT r FROM RecipeItem r WHERE r.inventoryItem.inventoryItemId=:id ORDER BY r.recipeItemId",RecipeItem.class).setParameter("id",id).setLockMode(jakarta.persistence.LockModeType.PESSIMISTIC_WRITE).getResultList().isEmpty(); requireRecipeItemInvariant(recipeReferenced,i.getItemType(),type,i.isActive(),active,i.getOnHandQuantity()); requireMappedFinishedGoodInvariant(mapped,type,active,i.getOnHandQuantity()); if(!i.getBaseUnit().equals(unit) && used(em,id)) throw new InventoryItemConflictException("Base unit is immutable after recipe or ledger use",i.getOnHandQuantity()); apply(i,code,name,type,unit,minimum,frequency,active); em.getTransaction().commit(); return dto(i); } catch(RuntimeException e){if(em.getTransaction().isActive())em.getTransaction().rollback();throw e;}finally{em.close();} }
    public Map<String,Object> mutate(int id,BigDecimal quantity,BigDecimal expected,String reason,String note,int adminId) { if(reason==null||reason.isBlank()||reason.length()>100||note!=null&&note.length()>500)throw new IllegalArgumentException("Invalid reason or note"); EntityManager em=entityManagers.get(); try { em.getTransaction().begin(); InventoryItem i=em.find(InventoryItem.class,id,jakarta.persistence.LockModeType.PESSIMISTIC_WRITE); if(i==null)throw new NoSuchElementException("Inventory item not found"); BigDecimal before=i.getOnHandQuantity(); if(before.compareTo(expected)!=0)throw new InventoryItemConflictException("Stale expected quantity",before); BigDecimal after=decimal(before.add(quantity),false); if(after.compareTo(i.getReservedQuantity())<0)throw new IllegalArgumentException("On-hand quantity cannot be below reserved quantity"); i.setOnHandQuantity(after); InventoryTransaction t=new InventoryTransaction(); t.setInventoryItem(i);t.setCreatedBy(em.find(User.class,adminId));t.setTransactionType("ADJUSTMENT");t.setQuantity(quantity);t.setQuantityBefore(before);t.setQuantityAfter(after);t.setReasonCode(reason);t.setNote(note);em.persist(t);em.getTransaction().commit();return dto(i); }catch(RuntimeException e){if(em.getTransaction().isActive())em.getTransaction().rollback();throw e;}finally{em.close();} }

    public static BigDecimal decimal(Object value,boolean positive){ try { BigDecimal d=value instanceof BigDecimal b?b:new BigDecimal(String.valueOf(value)); if(d.scale()>4||d.abs().compareTo(MAX)>0||positive&&d.signum()<=0||!positive&&d.signum()<0)throw new IllegalArgumentException("Invalid decimal"); return d.setScale(4,RoundingMode.UNNECESSARY); }catch(NumberFormatException|ArithmeticException e){throw new IllegalArgumentException("Invalid decimal",e);} }
    public static String unit(String unit){if(!UNITS.contains(unit))throw new IllegalArgumentException("Invalid base unit");return unit;}
    public static BigDecimal movingAverageCost(BigDecimal oldQuantity,BigDecimal oldCost,BigDecimal receivedQuantity,BigDecimal receivedUnitCost){if(oldQuantity==null||oldCost==null||receivedQuantity==null||receivedUnitCost==null||oldQuantity.signum()<0||oldCost.signum()<0||receivedQuantity.signum()<=0||receivedUnitCost.signum()<0)throw new IllegalArgumentException("Invalid costing input");return oldQuantity.multiply(oldCost).add(receivedQuantity.multiply(receivedUnitCost)).divide(oldQuantity.add(receivedQuantity),4,RoundingMode.HALF_UP);}
    private static void validate(String code,String name,String type,String unit,BigDecimal minimum,String frequency){if(code==null||!code.matches("[A-Z0-9-]{1,30}")||name==null||name.isBlank()||name.length()>150||!TYPES.contains(type)||!Set.of("DAILY","WEEKLY").contains(frequency))throw new IllegalArgumentException("Invalid inventory item");unit(unit);decimal(minimum,false);}
    private static void apply(InventoryItem i,String code,String name,String type,String unit,BigDecimal minimum,String frequency,boolean active){i.setInventoryCode(code);i.setName(name.trim());i.setItemType(type);i.setBaseUnit(unit);i.setMinimumQuantity(minimum);i.setCountFrequency(frequency);i.setActive(active);}
    private static boolean used(EntityManager em,int id){return em.createQuery("SELECT COUNT(r) FROM RecipeItem r WHERE r.inventoryItem.inventoryItemId=:id",Long.class).setParameter("id",id).getSingleResult()>0||em.createQuery("SELECT COUNT(t) FROM InventoryTransaction t WHERE t.inventoryItem.inventoryItemId=:id",Long.class).setParameter("id",id).getSingleResult()>0;}
    static void requireMappedFinishedGoodInvariant(boolean mapped,String type,boolean active,BigDecimal currentQuantity){if(mapped&&(!"FINISHED_GOOD".equals(type)||!active))throw new InventoryItemConflictException("Mapped finished-good item must remain active and FINISHED_GOOD",currentQuantity);}
    static void requireRecipeItemInvariant(boolean referenced,String oldType,String type,boolean oldActive,boolean active,BigDecimal currentQuantity){if(referenced&&(!oldType.equals(type)||oldActive&&!active))throw new InventoryItemConflictException("Mặt hàng đang được dùng trong công thức. Không thể đổi loại hoặc ngừng hoạt động; hãy cập nhật công thức trước.",currentQuantity);}
    public static Map<String,Object> dto(InventoryItem i){Map<String,Object>m=new LinkedHashMap<>();m.put("inventoryItemId",i.getInventoryItemId());m.put("inventoryCode",i.getInventoryCode());m.put("name",i.getName());m.put("itemType",i.getItemType());m.put("baseUnit",i.getBaseUnit());m.put("onHandQuantity",i.getOnHandQuantity());m.put("reservedQuantity",i.getReservedQuantity());m.put("availableQuantity",i.availableQuantity());m.put("minimumQuantity",i.getMinimumQuantity());m.put("countFrequency",i.getCountFrequency());m.put("averageUnitCost",i.getAverageUnitCost());m.put("lastCountedAt",i.getLastCountedAt());m.put("active",i.isActive());m.put("createdAt",i.getCreatedAt());m.put("updatedAt",i.getUpdatedAt());return m;}
}
