package service;

import entity.*;
import jakarta.persistence.*;
import utils.DatabaseUtil;
import java.math.*;
import java.time.LocalDateTime;
import java.util.*;
import java.util.function.Supplier;

public class GoodsReceiptService {
    private final Supplier<EntityManager> entityManagers;
    public GoodsReceiptService(){this(DatabaseUtil::getEntityManager);} GoodsReceiptService(Supplier<EntityManager> value){entityManagers=value;}
    public static BigDecimal baseQuantity(BigDecimal quantity,BigDecimal factor){return positive(quantity).multiply(positive(factor)).setScale(4,RoundingMode.HALF_UP);}
    public static BigDecimal lineTotal(BigDecimal quantity,BigDecimal price){return positive(quantity).multiply(positive(price)).setScale(4,RoundingMode.HALF_UP);}
    public static BigDecimal weightedAverage(BigDecimal oldQuantity,BigDecimal oldCost,BigDecimal receivedQuantity,BigDecimal receivedCost){return AdminInventoryService.movingAverageCost(oldQuantity,oldCost,receivedQuantity,receivedCost);}

    public List<Map<String,Object>> list(){EntityManager em=entityManagers.get();try{return em.createQuery("SELECT DISTINCT r FROM GoodsReceipt r LEFT JOIN FETCH r.items i LEFT JOIN FETCH i.inventoryItem ORDER BY r.receivedAt DESC,r.goodsReceiptId DESC",GoodsReceipt.class).getResultList().stream().map(GoodsReceiptService::dto).toList();}finally{em.close();}}
    public Map<String,Object> get(int id){EntityManager em=entityManagers.get();try{return dto(require(em,id,null));}finally{em.close();}}
    public Map<String,Object> create(Map<String,Object> body,int adminId){return save(0,body,adminId);}
    public Map<String,Object> update(int id,Map<String,Object> body,int adminId){return save(id,body,adminId);}
    private Map<String,Object> save(int id,Map<String,Object> body,int adminId){ReceiptInput input=parse(body);EntityManager em=entityManagers.get();try{em.getTransaction().begin();GoodsReceipt receipt=id==0?new GoodsReceipt():require(em,id,LockModeType.PESSIMISTIC_WRITE);if(id!=0&&!"DRAFT".equals(receipt.getStatus()))throw new IllegalStateException("Approved receipt is immutable");receipt.setSupplierName(input.supplierName());receipt.setInvoiceNumber(input.invoiceNumber());receipt.setReceivedAt(input.receivedAt());if(id==0){receipt.setCreatedBy(requireUser(em,adminId));em.persist(receipt);}else{receipt.getItems().clear();em.flush();}for(LineInput value:input.items()){InventoryItem item=em.find(InventoryItem.class,value.itemId());if(item==null)throw new NoSuchElementException("Inventory item not found");GoodsReceiptItem line=new GoodsReceiptItem();line.setReceipt(receipt);line.setInventoryItem(item);line.setPurchaseQuantity(value.quantity());line.setPurchaseUnit(value.unit());line.setConversionFactor(value.factor());line.setBaseQuantity(baseQuantity(value.quantity(),value.factor()));line.setPurchaseUnitPrice(value.price());line.setLineTotal(lineTotal(value.quantity(),value.price()));receipt.getItems().add(line);}em.flush();Map<String,Object> result=dto(receipt);em.getTransaction().commit();return result;}catch(RuntimeException e){rollback(em);throw e;}finally{em.close();}}
    public void delete(int id){EntityManager em=entityManagers.get();try{em.getTransaction().begin();GoodsReceipt receipt=require(em,id,LockModeType.PESSIMISTIC_WRITE);if(!"DRAFT".equals(receipt.getStatus()))throw new IllegalStateException("Approved receipt is immutable");em.remove(receipt);em.getTransaction().commit();}catch(RuntimeException e){rollback(em);throw e;}finally{em.close();}}
    public Map<String,Object> approve(int id,int adminId){EntityManager em=entityManagers.get();try{em.getTransaction().begin();GoodsReceipt receipt=require(em,id,LockModeType.PESSIMISTIC_WRITE);if(!"DRAFT".equals(receipt.getStatus()))throw new IllegalStateException("Receipt already approved");List<GoodsReceiptItem> lines=receipt.getItems().stream().sorted(Comparator.comparingInt(x->x.getInventoryItem().getInventoryItemId())).toList();for(GoodsReceiptItem line:lines){InventoryItem item=em.find(InventoryItem.class,line.getInventoryItem().getInventoryItemId(),LockModeType.PESSIMISTIC_WRITE);BigDecimal before=item.getOnHandQuantity(),oldCost=item.getAverageUnitCost(),base=line.getBaseQuantity(),unitCost=line.getLineTotal().divide(base,4,RoundingMode.HALF_UP),after=before.add(base).setScale(4,RoundingMode.HALF_UP),newCost=weightedAverage(before,oldCost,base,unitCost);line.setAverageCostBefore(oldCost);line.setAverageCostAfter(newCost);item.setOnHandQuantity(after);item.setAverageUnitCost(newCost);InventoryTransaction txn=transaction(item,"RECEIPT",base,before,after,unitCost,line.getLineTotal());txn.setGoodsReceipt(receipt);em.persist(txn);}receipt.setStatus("APPROVED");receipt.setApprovedBy(requireUser(em,adminId));receipt.setApprovedAt(LocalDateTime.now().withNano(0));em.flush();Map<String,Object> result=dto(receipt);em.getTransaction().commit();return result;}catch(RuntimeException e){rollback(em);throw e;}finally{em.close();}}
    static InventoryTransaction transaction(InventoryItem item,String type,BigDecimal quantity,BigDecimal before,BigDecimal after,BigDecimal unitCost,BigDecimal total){InventoryTransaction t=new InventoryTransaction();t.setInventoryItem(item);t.setTransactionType(type);t.setQuantity(quantity.setScale(4,RoundingMode.HALF_UP));t.setQuantityBefore(before.setScale(4,RoundingMode.HALF_UP));t.setQuantityAfter(after.setScale(4,RoundingMode.HALF_UP));t.setUnitCostSnapshot(unitCost.setScale(4,RoundingMode.HALF_UP));t.setTotalCost(total.abs().setScale(4,RoundingMode.HALF_UP));return t;}
    private static GoodsReceipt require(EntityManager em,int id,LockModeType lock){GoodsReceipt value=lock==null?em.find(GoodsReceipt.class,id):em.find(GoodsReceipt.class,id,lock);if(value==null)throw new NoSuchElementException("Goods receipt not found");value.getItems().size();return value;}
    private static User requireUser(EntityManager em,int id){User value=em.find(User.class,id);if(value==null)throw new IllegalArgumentException("Admin user not found");return value;}
    private static BigDecimal positive(BigDecimal value){if(value==null||value.signum()<=0||value.scale()>4)throw new IllegalArgumentException("Quantity and cost must be positive decimals with scale <= 4");return value;}
    @SuppressWarnings("unchecked") private static ReceiptInput parse(Map<String,Object>b){if(b==null||!Set.of("supplierName","invoiceNumber","receivedAt","items").containsAll(b.keySet()))throw new IllegalArgumentException("Invalid receipt fields");String supplier=text(b.get("supplierName"),150,true),invoice=text(b.get("invoiceNumber"),100,false);LocalDateTime received;try{received=LocalDateTime.parse(text(b.get("receivedAt"),50,true));}catch(RuntimeException e){throw new IllegalArgumentException("Invalid receivedAt",e);}if(!(b.get("items") instanceof List<?> raw)||raw.isEmpty())throw new IllegalArgumentException("Receipt items are required");Set<Integer>ids=new HashSet<>();List<LineInput>lines=new ArrayList<>();for(Object value:raw){if(!(value instanceof Map<?,?> map)||!Set.of("inventoryItemId","purchaseQuantity","purchaseUnit","conversionFactor","purchaseUnitPrice").containsAll(map.keySet())||map.size()!=5)throw new IllegalArgumentException("Invalid receipt item");int itemId=AdminInventoryItemServletAccess.positiveInt(map.get("inventoryItemId"),"inventoryItemId");if(!ids.add(itemId))throw new IllegalArgumentException("Duplicate inventory item");lines.add(new LineInput(itemId,positive(decimal(map.get("purchaseQuantity"))),text(map.get("purchaseUnit"),30,true),positive(decimal(map.get("conversionFactor"))),positive(decimal(map.get("purchaseUnitPrice")))));}return new ReceiptInput(supplier,invoice,received,lines);}
    private static BigDecimal decimal(Object v){try{return new BigDecimal(String.valueOf(v));}catch(RuntimeException e){throw new IllegalArgumentException("Invalid decimal",e);}}
    private static String text(Object v,int max,boolean required){if(v==null&&!required)return null;if(!(v instanceof String s)||required&&s.isBlank()||s.length()>max)throw new IllegalArgumentException("Invalid text");return s.trim();}
    public static Map<String,Object> dto(GoodsReceipt r){Map<String,Object>m=new LinkedHashMap<>();m.put("goodsReceiptId",r.getGoodsReceiptId());m.put("supplierName",r.getSupplierName());m.put("invoiceNumber",r.getInvoiceNumber());m.put("receivedAt",r.getReceivedAt());m.put("status",r.getStatus());m.put("items",r.getItems().stream().map(GoodsReceiptService::itemDto).toList());m.put("createdAt",r.getCreatedAt());m.put("approvedAt",r.getApprovedAt());return m;}
    private static Map<String,Object> itemDto(GoodsReceiptItem i){Map<String,Object>m=new LinkedHashMap<>();m.put("goodsReceiptItemId",i.getGoodsReceiptItemId());m.put("inventoryItemId",i.getInventoryItem().getInventoryItemId());m.put("purchaseQuantity",i.getPurchaseQuantity());m.put("purchaseUnit",i.getPurchaseUnit());m.put("conversionFactor",i.getConversionFactor());m.put("baseQuantity",i.getBaseQuantity());m.put("purchaseUnitPrice",i.getPurchaseUnitPrice());m.put("lineTotal",i.getLineTotal());m.put("averageCostBefore",i.getAverageCostBefore());m.put("averageCostAfter",i.getAverageCostAfter());return m;}
    private static void rollback(EntityManager em){if(em.getTransaction().isActive())em.getTransaction().rollback();}
    private record ReceiptInput(String supplierName,String invoiceNumber,LocalDateTime receivedAt,List<LineInput>items){} private record LineInput(int itemId,BigDecimal quantity,String unit,BigDecimal factor,BigDecimal price){}
}
