package service;

import jakarta.persistence.EntityManager;
import utils.DatabaseUtil;
import java.math.*;
import java.time.*;
import java.util.*;
import java.util.function.Supplier;

public class InventoryReportService {
    private final Supplier<EntityManager> entityManagers;
    public InventoryReportService(){this(DatabaseUtil::getEntityManager);} InventoryReportService(Supplier<EntityManager> value){entityManagers=value;}

    public Map<String,BigDecimal> summary(LocalDate from,LocalDate to){range(from,to);EntityManager em=entityManagers.get();try{LocalDateTime end=end(to);List<Map<String,Object>>period=transactions(em,from.atStartOfDay(),end);List<Map<String,Object>>history=transactions(em,null,end);return summarize(period,endingValue(history));}finally{em.close();}}
    public List<Map<String,Object>> itemLoss(LocalDate from,LocalDate to){range(from,to);EntityManager em=entityManagers.get();try{return itemLossRows(transactions(em,from.atStartOfDay(),end(to)));}finally{em.close();}}
    public List<Map<String,Object>> menuCost(){EntityManager em=entityManagers.get();try{return em.createQuery("SELECT v.variantId,v.variantName,v.sku,r.yieldQuantity,SUM(ri.quantity*i.averageUnitCost) FROM Recipe r JOIN r.variant v JOIN r.items ri JOIN ri.inventoryItem i WHERE r.active=true GROUP BY v.variantId,v.variantName,v.sku,r.yieldQuantity ORDER BY v.variantId",Object[].class).getResultList().stream().map(InventoryReportService::menuCostRow).toList();}finally{em.close();}}

    private static List<Map<String,Object>> transactions(EntityManager em,LocalDateTime from,LocalDateTime to){String where=from==null?" WHERE t.createdAt<:to":" WHERE t.createdAt>=:from AND t.createdAt<:to";var query=em.createQuery("SELECT i.inventoryItemId,i.inventoryCode,i.name,t.transactionType,t.quantity,t.quantityBefore,t.quantityAfter,t.unitCostSnapshot,t.totalCost,s.stockCountId FROM InventoryTransaction t JOIN t.inventoryItem i LEFT JOIN t.stockCount s"+where+" ORDER BY i.inventoryItemId,t.createdAt,t.inventoryTransactionId",Object[].class).setParameter("to",to);if(from!=null)query.setParameter("from",from);return query.getResultList().stream().map(InventoryReportService::transactionRow).toList();}
    private static Map<String,Object> transactionRow(Object[]r){Map<String,Object>m=new LinkedHashMap<>();m.put("inventoryItemId",r[0]);m.put("inventoryCode",r[1]);m.put("name",r[2]);m.put("transactionType",r[3]);m.put("quantity",r[4]);m.put("quantityBefore",r[5]);m.put("quantityAfter",r[6]);m.put("unitCostSnapshot",r[7]);m.put("totalCost",r[8]);if(r[9]!=null)m.put("stockCountId",r[9]);return m;}

    public static BigDecimal endingValue(List<Map<String,Object>>rows){Map<Integer,BigDecimal>quantities=new HashMap<>(),costs=new HashMap<>();for(Map<String,Object>r:rows){String type=(String)r.get("transactionType");if("RESERVE".equals(type)||"RELEASE".equals(type))continue;int id=(int)r.get("inventoryItemId");BigDecimal after=(BigDecimal)r.get("quantityAfter"),snapshot=(BigDecimal)r.get("unitCostSnapshot");if(snapshot!=null){if("RECEIPT".equals(type)){BigDecimal oldQuantity=quantities.getOrDefault(id,BigDecimal.ZERO),oldCost=costs.getOrDefault(id,BigDecimal.ZERO),received=((BigDecimal)r.get("quantity")).abs();costs.put(id,AdminInventoryService.movingAverageCost(oldQuantity,oldCost,received,snapshot));}else costs.put(id,snapshot);}if(after!=null)quantities.put(id,after);}BigDecimal total=zero();for(Map.Entry<Integer,BigDecimal>entry:quantities.entrySet())total=total.add(entry.getValue().multiply(costs.getOrDefault(entry.getKey(),BigDecimal.ZERO)));return scale(total);}
    public static List<Map<String,Object>> itemLossRows(List<Map<String,Object>>rows){Map<Integer,Map<String,Object>>result=new LinkedHashMap<>();for(Map<String,Object>r:rows){String type=(String)r.get("transactionType");BigDecimal quantity=(BigDecimal)r.get("quantity");boolean waste="WASTE".equals(type),countLoss="ADJUSTMENT".equals(type)&&quantity.signum()<0&&r.get("stockCountId")!=null;if(!waste&&!countLoss)continue;int id=(int)r.get("inventoryItemId");Map<String,Object>line=result.computeIfAbsent(id,key->{Map<String,Object>m=new LinkedHashMap<>();m.put("inventoryItemId",key);m.put("inventoryCode",r.get("inventoryCode"));m.put("name",r.get("name"));m.put("wasteQuantity",zero());m.put("wasteCost",zero());m.put("stockCountLossQuantity",zero());m.put("stockCountLossCost",zero());m.put("totalLossCost",zero());return m;});String quantityKey=waste?"wasteQuantity":"stockCountLossQuantity",costKey=waste?"wasteCost":"stockCountLossCost";BigDecimal cost=(BigDecimal)r.get("totalCost");if(cost==null)cost=BigDecimal.ZERO;line.put(quantityKey,scale(((BigDecimal)line.get(quantityKey)).add(quantity.abs())));line.put(costKey,scale(((BigDecimal)line.get(costKey)).add(cost)));line.put("totalLossCost",scale(((BigDecimal)line.get("totalLossCost")).add(cost)));}return new ArrayList<>(result.values());}
    public static Map<String,Object> menuCostRow(Object[]r){BigDecimal yield=(BigDecimal)r[3],cost=scale((BigDecimal)r[4]);Map<String,Object>m=new LinkedHashMap<>();m.put("variantId",r[0]);m.put("variantName",r[1]);m.put("sku",r[2]);m.put("yieldQuantity",scale(yield));m.put("recipeCost",cost);m.put("costPerServing",cost.divide(yield,4,RoundingMode.HALF_UP));return m;}
    public static Map<String,BigDecimal> summarize(List<Map<String,Object>>rows,BigDecimal ending){BigDecimal purchase=zero(),consume=zero(),waste=zero(),loss=zero(),gain=zero();for(Map<String,Object>r:rows){String type=(String)r.get("transactionType");BigDecimal quantity=(BigDecimal)r.get("quantity"),cost=(BigDecimal)r.get("totalCost");if(cost==null)continue;if("RECEIPT".equals(type))purchase=purchase.add(cost);else if("CONSUME".equals(type))consume=consume.add(cost);else if("WASTE".equals(type))waste=waste.add(cost);else if("ADJUSTMENT".equals(type)&&r.get("stockCountId")!=null){if(quantity.signum()<0)loss=loss.add(cost);else gain=gain.add(cost);}}BigDecimal totalLoss=waste.add(loss),rate=consume.signum()>0?totalLoss.multiply(new BigDecimal("100")).divide(consume,4,RoundingMode.HALF_UP):zero();Map<String,BigDecimal>m=new LinkedHashMap<>();m.put("purchaseCost",scale(purchase));m.put("consumptionCost",scale(consume));m.put("wasteCost",scale(waste));m.put("stockCountLossCost",scale(loss));m.put("stockCountGainCost",scale(gain));m.put("totalLossCost",scale(totalLoss));m.put("endingInventoryValue",scale(ending));m.put("lossRate",scale(rate));return m;}
    private static void range(LocalDate from,LocalDate to){if(from==null||to==null||from.isAfter(to))throw new IllegalArgumentException("Invalid date range");}
    private static LocalDateTime end(LocalDate to){return to.equals(LocalDate.MAX)?LocalDateTime.MAX:to.plusDays(1).atStartOfDay();}
    private static BigDecimal zero(){return new BigDecimal("0.0000");} private static BigDecimal scale(BigDecimal v){return v.setScale(4,RoundingMode.HALF_UP);}
}
