package service;

import entity.*;
import jakarta.persistence.*;
import utils.DatabaseUtil;
import java.math.*;
import java.time.*;
import java.util.*;
import java.util.function.Supplier;

public class StockCountService {
    private final Supplier<EntityManager> entityManagers;private final ActivityLogService activityLogService=new ActivityLogService();
    public StockCountService(){this(DatabaseUtil::getEntityManager);} StockCountService(Supplier<EntityManager> value){entityManagers=value;}
    public static BigDecimal variance(BigDecimal actual,BigDecimal theoretical){return actual.subtract(theoretical).setScale(4,RoundingMode.HALF_UP);}
    public static BigDecimal varianceCost(BigDecimal variance,BigDecimal unitCost){return variance.multiply(unitCost).abs().setScale(4,RoundingMode.HALF_UP);}
    public static void requireReservedFloor(BigDecimal actual,BigDecimal reserved){if(actual.compareTo(reserved)<0)throw new IllegalArgumentException("Actual quantity cannot be below reserved quantity");}
    public static void requireCurrentCost(BigDecimal snapshot,BigDecimal current){if(snapshot==null||current==null||snapshot.compareTo(current)!=0)throw new IllegalStateException("Stale average unit cost");}
    public List<Map<String,Object>> list(){EntityManager em=entityManagers.get();try{return em.createQuery("SELECT DISTINCT c FROM StockCount c LEFT JOIN FETCH c.items i LEFT JOIN FETCH i.inventoryItem ORDER BY c.countDate DESC,c.stockCountId DESC",StockCount.class).getResultList().stream().map(StockCountService::dto).toList();}finally{em.close();}}
    public Map<String,Object> get(int id){EntityManager em=entityManagers.get();try{return dto(require(em,id,null));}finally{em.close();}}
    public Map<String,Object> create(LocalDate date,List<Integer> itemIds,int adminId){if(date==null||itemIds==null||itemIds.isEmpty()||itemIds.stream().anyMatch(Objects::isNull)||new HashSet<>(itemIds).size()!=itemIds.size())throw new IllegalArgumentException("Invalid stock count");EntityManager em=entityManagers.get();try{em.getTransaction().begin();User user=em.find(User.class,adminId);if(user==null)throw new IllegalArgumentException("Admin user not found");List<InventoryItem>items=new ArrayList<>();for(Integer itemId:itemIds.stream().sorted().toList()){InventoryItem item=em.find(InventoryItem.class,itemId,LockModeType.PESSIMISTIC_READ);if(item==null||!item.isActive()||!"INGREDIENT".equals(item.getItemType()))throw new IllegalArgumentException("Stock count accepts active ingredients only");items.add(item);}StockCount count=new StockCount();count.setCountDate(date);count.setFrequency("DAILY");count.setCreatedBy(user);em.persist(count);for(InventoryItem item:items){StockCountItem line=new StockCountItem();line.setStockCount(count);line.setInventoryItem(item);line.setTheoreticalQuantity(item.getOnHandQuantity().setScale(4,RoundingMode.HALF_UP));line.setUnitCostSnapshot(item.getAverageUnitCost().setScale(4,RoundingMode.HALF_UP));line.setReservedQuantitySnapshot(item.getReservedQuantity().setScale(4,RoundingMode.HALF_UP));count.getItems().add(line);em.persist(line);}em.flush();Map<String,Object>result=dto(count);em.getTransaction().commit();return result;}catch(RuntimeException e){rollback(em);throw e;}finally{em.close();}}
    public Map<String,Object> update(int id,List<Map<String,Object>> inputs){if(inputs==null||inputs.isEmpty())throw new IllegalArgumentException("Count items are required");EntityManager em=entityManagers.get();try{em.getTransaction().begin();StockCount count=require(em,id,LockModeType.PESSIMISTIC_WRITE);if(!"DRAFT".equals(count.getStatus()))throw new IllegalStateException("Approved stock count is immutable");Map<Integer,StockCountItem>lines=new HashMap<>();for(StockCountItem line:count.getItems())lines.put(line.getInventoryItem().getInventoryItemId(),line);Set<Integer>seen=new HashSet<>();for(Map<String,Object>b:inputs){if(b==null||!Set.of("inventoryItemId","theoreticalQuantity","actualQuantity","reasonCode","note").containsAll(b.keySet()))throw new IllegalArgumentException("Invalid count item");int itemId=AdminInventoryItemServletAccess.positiveInt(b.get("inventoryItemId"),"inventoryItemId");StockCountItem line=lines.get(itemId);if(line==null||!seen.add(itemId))throw new IllegalArgumentException("Invalid inventory item");BigDecimal theoretical=decimal(b.get("theoreticalQuantity"),false),actual=decimal(b.get("actualQuantity"),false);if(line.getTheoreticalQuantity().compareTo(theoretical)!=0)throw new IllegalStateException("Stale theoretical quantity");line.setActualQuantity(actual);line.setReasonCode(text(b.get("reasonCode"),50));line.setNote(text(b.get("note"),500));}if(seen.size()!=lines.size())throw new IllegalArgumentException("All count items are required");em.flush();Map<String,Object>result=dto(count);em.getTransaction().commit();return result;}catch(RuntimeException e){rollback(em);throw e;}finally{em.close();}}
    public Map<String,Object> approve(int id,int adminId){EntityManager em=entityManagers.get();try{em.getTransaction().begin();StockCount count=require(em,id,LockModeType.PESSIMISTIC_WRITE);if(!"DRAFT".equals(count.getStatus()))throw new IllegalStateException("Stock count already approved");List<StockCountItem>lines=count.getItems().stream().sorted(Comparator.comparingInt(x->x.getInventoryItem().getInventoryItemId())).toList();if(lines.stream().anyMatch(x->x.getActualQuantity()==null))throw new IllegalArgumentException("Actual quantity is required");for(StockCountItem line:lines){InventoryItem item=em.find(InventoryItem.class,line.getInventoryItem().getInventoryItemId(),LockModeType.PESSIMISTIC_WRITE);if(item.getOnHandQuantity().compareTo(line.getTheoreticalQuantity())!=0)throw new IllegalStateException("Stale theoretical quantity");requireCurrentCost(line.getUnitCostSnapshot(),item.getAverageUnitCost());}
        LocalDateTime now=LocalDateTime.now().withNano(0);for(StockCountItem line:lines){InventoryItem item=line.getInventoryItem();BigDecimal before=item.getOnHandQuantity(),actual=line.getActualQuantity().setScale(4,RoundingMode.HALF_UP),delta=variance(actual,before),cost=line.getUnitCostSnapshot();line.setVarianceQuantity(delta);line.setVarianceCost(varianceCost(delta,cost));item.setOnHandQuantity(actual);item.setLastCountedAt(now);if(delta.signum()!=0){InventoryTransaction txn=GoodsReceiptService.transaction(item,"ADJUSTMENT",delta,before,actual,cost,line.getVarianceCost());txn.setStockCount(count);txn.setReasonCode(line.getReasonCode());txn.setNote(line.getNote());em.persist(txn);}}User user=em.find(User.class,adminId);if(user==null)throw new IllegalArgumentException("Admin user not found");count.setStatus("APPROVED");count.setApprovedBy(user);count.setApprovedAt(now);em.flush();activityLogService.append(em,adminId,"STOCK_COUNT_APPROVED","STOCK_COUNT",id,Map.of("countDate",count.getCountDate().toString(),"frequency",count.getFrequency()));Map<String,Object>result=dto(count);em.getTransaction().commit();return result;}catch(RuntimeException e){rollback(em);throw e;}finally{em.close();}}
    private static StockCount require(EntityManager em,int id,LockModeType lock){StockCount value=lock==null?em.find(StockCount.class,id):em.find(StockCount.class,id,lock);if(value==null)throw new NoSuchElementException("Stock count not found");value.getItems().size();return value;}
    private static BigDecimal decimal(Object value,boolean positive){try{BigDecimal d=new BigDecimal(String.valueOf(value));if(d.scale()>4||(positive?d.signum()<=0:d.signum()<0))throw new IllegalArgumentException("Invalid decimal");return d.setScale(4,RoundingMode.UNNECESSARY);}catch(NumberFormatException|ArithmeticException e){throw new IllegalArgumentException("Invalid decimal",e);}}
    private static String text(Object value,int max){if(value==null)return null;if(!(value instanceof String s)||s.length()>max)throw new IllegalArgumentException("Invalid text");return s.trim();}
    public static Map<String,Object> dto(StockCount c){Map<String,Object>m=new LinkedHashMap<>();m.put("stockCountId",c.getStockCountId());m.put("countDate",c.getCountDate());m.put("frequency",c.getFrequency());m.put("status",c.getStatus());m.put("items",c.getItems().stream().map(StockCountService::itemDto).toList());m.put("createdAt",c.getCreatedAt());m.put("approvedAt",c.getApprovedAt());return m;}
    private static Map<String,Object> itemDto(StockCountItem i){Map<String,Object>m=new LinkedHashMap<>();m.put("stockCountItemId",i.getStockCountItemId());m.put("inventoryItemId",i.getInventoryItem().getInventoryItemId());m.put("theoreticalQuantity",i.getTheoreticalQuantity());m.put("actualQuantity",i.getActualQuantity());m.put("varianceQuantity",i.getVarianceQuantity());m.put("unitCostSnapshot",i.getUnitCostSnapshot());m.put("reservedQuantitySnapshot",i.getReservedQuantitySnapshot());m.put("varianceCost",i.getVarianceCost());m.put("reasonCode",i.getReasonCode());m.put("note",i.getNote());return m;}
    private static void rollback(EntityManager em){if(em.getTransaction().isActive())em.getTransaction().rollback();}
}
