SET NOCOUNT ON;
SET XACT_ABORT ON;
IF DB_NAME()<>N'DemoDatabase' THROW 51900, 'Presentation demo validator target must be DemoDatabase', 1;
IF NOT EXISTS(SELECT 1 FROM dbo.SchemaMigrationHistory WHERE migration_id='065_warehouse_operations_redesign') THROW 51901, 'Migration 065 is required', 1;

DECLARE @ExpectedProducts int=20;
DECLARE @ExpectedIngredients int=20;
DECLARE @ExpectedRecipeLines int=40;
DECLARE @ExpectedOrders int=45;
DECLARE @ExpectedDeliveredLast7Days int=7;
DECLARE @ExpectedDeliveredToday int=1;
DECLARE @ExpectedRefundOrders int=3;
DECLARE @ExpectedCodSettlements int=4;
DECLARE @ExpectedDemoShifts int=9;
DECLARE @ExpectedPayRates int=2;

IF (SELECT COUNT(*) FROM dbo.Product WHERE name LIKE N'DEMO-PRES-PROD-%')<>@ExpectedProducts THROW 51902, 'Expected 20 presentation products', 1;
IF (SELECT COUNT(*) FROM dbo.ProductVariant WHERE sku LIKE 'DEMO-PRES-SKU-%')<>@ExpectedProducts THROW 51903, 'Expected 20 presentation variants', 1;
IF EXISTS(SELECT 1 FROM dbo.Product p WHERE p.name LIKE N'DEMO-PRES-PROD-%' AND NOT EXISTS(SELECT 1 FROM dbo.ProductVariant v WHERE v.product_id=p.product_id AND v.sku LIKE 'DEMO-PRES-SKU-%')) THROW 51904, 'Presentation product without variant', 1;
IF (SELECT COUNT(*) FROM dbo.InventoryItem WHERE inventory_code LIKE 'DEMO-PRES-ING-%')<>@ExpectedIngredients THROW 51905, 'Expected 20 presentation ingredients', 1;
IF EXISTS(SELECT 1 FROM dbo.InventoryItem WHERE inventory_code LIKE 'DEMO-PRES-ING-%' AND (item_type<>'INGREDIENT' OR base_unit NOT IN('G','ML','PIECE') OR on_hand_quantity<0 OR reserved_quantity<0 OR minimum_quantity<0 OR average_unit_cost<0 OR active<>1)) THROW 51906, 'Presentation ingredient invalid', 1;
IF (SELECT COUNT(*) FROM dbo.RecipeItem ri JOIN dbo.Recipe r ON r.recipe_id=ri.recipe_id JOIN dbo.ProductVariant v ON v.variant_id=r.variant_id WHERE v.sku LIKE 'DEMO-PRES-SKU-%')<>@ExpectedRecipeLines THROW 51907, 'Expected 40 presentation recipe lines', 1;
IF EXISTS(SELECT 1 FROM dbo.ProductVariant v LEFT JOIN dbo.Recipe r ON r.variant_id=v.variant_id AND r.active=1 WHERE v.sku LIKE 'DEMO-PRES-SKU-%' AND (v.inventory_mode<>'INGREDIENT' OR r.recipe_id IS NULL OR r.yield_quantity<=0)) THROW 51908, 'Presentation recipe invalid', 1;
IF EXISTS(SELECT 1 FROM dbo.RecipeItem ri JOIN dbo.Recipe r ON r.recipe_id=ri.recipe_id JOIN dbo.ProductVariant v ON v.variant_id=r.variant_id LEFT JOIN dbo.InventoryItem i ON i.inventory_item_id=ri.inventory_item_id WHERE v.sku LIKE 'DEMO-PRES-SKU-%' AND (i.inventory_item_id IS NULL OR i.inventory_code NOT LIKE 'DEMO-PRES-ING-%' OR ri.quantity<=0)) THROW 51909, 'Presentation recipe item invalid or orphaned', 1;
IF (SELECT COUNT(*) FROM dbo.Orders WHERE order_code LIKE 'DEMO-PRES-ORD-%')<>@ExpectedOrders THROW 51910, 'Expected 45 presentation orders', 1;
IF EXISTS(SELECT 1 FROM dbo.Orders WHERE order_code LIKE 'DEMO-PRES-ORD-%' AND created_at<DATEADD(day,-30,SYSDATETIME())) THROW 51911, 'Presentation order outside 30-day window', 1;
IF EXISTS(SELECT 1 FROM dbo.Orders o OUTER APPLY(SELECT SUM(oi.total_price) item_total FROM dbo.OrderItem oi WHERE oi.order_id=o.order_id)x WHERE o.order_code LIKE 'DEMO-PRES-ORD-%' AND (x.item_total IS NULL OR o.total_amount<>x.item_total OR o.final_amount<>o.total_amount+o.shipping_fee+o.service_fee-o.discount_amount)) THROW 51912, 'Presentation order amount inconsistency', 1;
IF EXISTS(SELECT 1 FROM dbo.OrderItem oi JOIN dbo.Orders o ON o.order_id=oi.order_id WHERE o.order_code LIKE 'DEMO-PRES-ORD-%' AND (oi.product_id IS NULL OR oi.variant_id IS NULL OR oi.quantity<=0 OR oi.total_price<>oi.quantity*oi.unit_price OR oi.total_cost_snapshot<>oi.quantity*oi.unit_cost_snapshot)) THROW 51913, 'Presentation order item invalid', 1;
IF EXISTS(SELECT 1 FROM dbo.Orders o WHERE o.order_code LIKE 'DEMO-PRES-ORD-%' AND ((o.payment_status='PAID' AND o.paid_at IS NULL) OR (o.payment_status<>'PAID' AND o.paid_at IS NOT NULL) OR (o.order_status='DELIVERED' AND o.delivered_at IS NULL) OR (o.order_status='CANCELLED' AND o.cancelled_at IS NULL) OR (o.order_status IN('DELIVERY_FAILED','RETURNED_TO_STORE') AND (o.delivery_failed_at IS NULL OR o.delivery_failure_code IS NULL)) OR (o.order_status='RETURNED_TO_STORE' AND o.returned_to_store_at IS NULL))) THROW 51914, 'Presentation amount/status timeline inconsistency', 1;
IF (SELECT COUNT(DISTINCT order_status) FROM dbo.Orders WHERE order_code LIKE 'DEMO-PRES-ORD-%')<8 OR (SELECT COUNT(DISTINCT payment_method) FROM dbo.Orders WHERE order_code LIKE 'DEMO-PRES-ORD-%')<>2 THROW 51915, 'Presentation order diversity insufficient', 1;
IF EXISTS(SELECT 1 FROM dbo.Orders o WHERE o.order_code LIKE 'DEMO-PRES-ORD-%' AND (NOT EXISTS(SELECT 1 FROM dbo.OrderItem oi WHERE oi.order_id=o.order_id) OR NOT EXISTS(SELECT 1 FROM dbo.OrderStatusHistory h WHERE h.order_id=o.order_id) OR NOT EXISTS(SELECT 1 FROM dbo.PaymentAttempt p WHERE p.order_id=o.order_id AND p.amount=o.final_amount))) THROW 51916, 'Presentation order child data missing', 1;
IF (SELECT COUNT(*) FROM dbo.Orders WHERE order_code LIKE 'DEMO-PRES-ORD-%' AND order_status='DELIVERED' AND delivered_at>=DATEADD(day,-6,CAST(SYSDATETIME() AS date)) AND delivered_at<DATEADD(day,1,CAST(SYSDATETIME() AS date)))<>@ExpectedDeliveredLast7Days THROW 51921, 'Expected delivered presentation orders across the last 7 days', 1;
IF (SELECT COUNT(*) FROM dbo.Orders WHERE order_code LIKE 'DEMO-PRES-ORD-%' AND order_status='DELIVERED' AND CAST(delivered_at AS date)=CAST(SYSDATETIME() AS date))<>@ExpectedDeliveredToday THROW 51922, 'Expected one delivered presentation order today', 1;
IF (SELECT COUNT(DISTINCT oi.product_id) FROM dbo.OrderItem oi JOIN dbo.Orders o ON o.order_id=oi.order_id WHERE o.order_code LIKE 'DEMO-PRES-ORD-%' AND o.order_status='DELIVERED' AND o.delivered_at>=DATEADD(day,-6,CAST(SYSDATETIME() AS date)) AND o.delivered_at<DATEADD(day,1,CAST(SYSDATETIME() AS date)))<5 THROW 51923, 'Expected top-product presentation coverage in the last 7 days', 1;
IF (SELECT COUNT(*) FROM dbo.Orders WHERE order_code LIKE 'DEMO-PRES-ORD-%' AND refund_status IS NOT NULL)<>@ExpectedRefundOrders THROW 51924, 'Expected presentation refund diversity', 1;
IF EXISTS(SELECT 1 FROM dbo.Orders WHERE order_code LIKE 'DEMO-PRES-ORD-%' AND ((refund_status='REFUNDED' AND (refund_amount IS NULL OR refunded_at IS NULL OR refund_processed_by IS NULL OR refund_reference IS NULL)) OR (refund_status='PENDING' AND refunded_at IS NOT NULL))) THROW 51925, 'Presentation refund timeline invalid', 1;
IF (SELECT COUNT(*) FROM dbo.CodSettlement c JOIN dbo.WorkShift w ON w.shift_id=c.shift_id WHERE w.attendance_note LIKE N'DEMO-PRES-SHIFT-COD-%')<>@ExpectedCodSettlements THROW 51926, 'Expected presentation COD settlements', 1;
IF (SELECT COUNT(DISTINCT c.status) FROM dbo.CodSettlement c JOIN dbo.WorkShift w ON w.shift_id=c.shift_id WHERE w.attendance_note LIKE N'DEMO-PRES-SHIFT-COD-%')<>4 THROW 51927, 'Expected all COD settlement states', 1;
IF (SELECT COUNT(*) FROM dbo.WorkShift WHERE attendance_note LIKE N'DEMO-PRES-SHIFT%')<>@ExpectedDemoShifts THROW 51928, 'Expected presentation shifts', 1;
IF (SELECT COUNT(*) FROM dbo.StaffPayRate r WHERE r.effective_from=DATEADD(day,-30,CAST(SYSDATETIME() AS date)) AND r.user_id IN(SELECT DISTINCT user_id FROM dbo.WorkShift WHERE attendance_note LIKE N'DEMO-PRES-SHIFT%'))<>@ExpectedPayRates THROW 51929, 'Expected presentation pay rates', 1;
IF NOT EXISTS(SELECT 1 FROM dbo.WorkShift WHERE attendance_note LIKE N'DEMO-PRES-SHIFT%' AND attendance_status='PENDING') OR NOT EXISTS(SELECT 1 FROM dbo.WorkShift WHERE attendance_note LIKE N'DEMO-PRES-SHIFT%' AND attendance_status='APPROVED' AND pay_snapshot_status='CALCULATED' AND total_pay_amount=regular_pay_amount+overtime_pay_amount) THROW 51930, 'Presentation attendance diversity invalid', 1;
IF EXISTS(SELECT 1 FROM dbo.InventoryTransaction t JOIN dbo.InventoryItem i ON i.inventory_item_id=t.inventory_item_id WHERE i.inventory_code LIKE 'DEMO-PRES-ING-%' AND (t.quantity=0 OR t.quantity_before<0 OR t.quantity_after<0 OR (t.quantity_before IS NOT NULL AND t.quantity_after IS NOT NULL AND t.quantity_after<>t.quantity_before+t.quantity) OR t.unit_cost_snapshot<0 OR t.total_cost<0)) THROW 51917, 'Presentation inventory transaction invalid', 1;
IF NOT EXISTS(SELECT 1 FROM dbo.GoodsReceipt g WHERE g.invoice_number LIKE N'DEMO-PRES-REC-%' AND g.status='APPROVED' AND EXISTS(SELECT 1 FROM dbo.GoodsReceiptItem gi WHERE gi.goods_receipt_id=g.goods_receipt_id)) THROW 51918, 'Presentation receipt missing', 1;
IF NOT EXISTS(SELECT 1 FROM dbo.StockCount c WHERE c.status='APPROVED' AND EXISTS(SELECT 1 FROM dbo.StockCountItem ci JOIN dbo.InventoryItem i ON i.inventory_item_id=ci.inventory_item_id WHERE ci.stock_count_id=c.stock_count_id AND i.inventory_code LIKE 'DEMO-PRES-ING-%')) THROW 51919, 'Presentation stock count missing', 1;
IF EXISTS(SELECT 1 FROM dbo.StockCountItem ci JOIN dbo.InventoryItem i ON i.inventory_item_id=ci.inventory_item_id WHERE i.inventory_code LIKE 'DEMO-PRES-ING-%' AND (ci.theoretical_quantity<0 OR ci.actual_quantity<0 OR ci.variance_quantity<>ci.actual_quantity-ci.theoretical_quantity)) THROW 51920, 'Presentation stock count invalid', 1;

SELECT COUNT(*) product_count FROM dbo.Product WHERE name LIKE N'DEMO-PRES-PROD-%';
SELECT COUNT(*) ingredient_count FROM dbo.InventoryItem WHERE inventory_code LIKE 'DEMO-PRES-ING-%';
SELECT COUNT(*) order_count,SUM(CASE WHEN order_status='DELIVERED' THEN final_amount ELSE 0 END) delivered_revenue_30_days FROM dbo.Orders WHERE order_code LIKE 'DEMO-PRES-ORD-%';
PRINT 'Presentation demo seed validation passed';
