<script setup>
import { nextTick, onBeforeUnmount, ref, watch } from 'vue';
const props = defineProps({ notice: { type: Object, default: null } });
const emit = defineEmits(['close']);
const dialog = ref(null);
const closeButton = ref(null);
let previousOverflow = '';
function close() { emit('close'); }
function keydown(event) { if (event.key === 'Escape') { event.preventDefault(); close(); return; } if (event.key !== 'Tab' || !dialog.value) return; const nodes=[...dialog.value.querySelectorAll('button:not([disabled]),a[href]')]; if (!nodes.length) return; const first=nodes[0],last=nodes.at(-1); if (event.shiftKey && document.activeElement===first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement===last) { event.preventDefault(); first.focus(); } }
watch(() => props.notice, async value => { if (value) { previousOverflow=document.body.style.overflow;document.body.style.overflow='hidden';document.addEventListener('keydown',keydown);await nextTick();closeButton.value?.focus(); } else { document.removeEventListener('keydown',keydown);document.body.style.overflow=previousOverflow; } }, { immediate: true });
onBeforeUnmount(() => { document.removeEventListener('keydown',keydown);if(props.notice)document.body.style.overflow=previousOverflow; });
</script>
<template><Teleport to="body"><div v-if="notice" class="notice-backdrop" @mousedown.self="close"><section ref="dialog" class="notice-dialog" role="dialog" aria-modal="true" aria-labelledby="morning-notice-title"><button ref="closeButton" type="button" class="notice-close" aria-label="Đóng thông báo" @click="close">×</button><img v-if="notice.imageUrl" :src="notice.imageUrl" alt="" @error="$event.currentTarget.hidden=true" /><div class="notice-copy"><p>THÔNG BÁO TỪ FASTGUY</p><h2 id="morning-notice-title">{{ notice.title }}</h2><span>{{ notice.message }}</span><div class="notice-actions"><a v-if="notice.link" class="notice-primary" :href="notice.link">{{ notice.ctaLabel }}</a><button type="button" @click="close">Đã hiểu</button></div></div></section></div></Teleport></template>
<style scoped>.notice-backdrop{position:fixed;z-index:200;inset:0;display:grid;place-items:center;padding:22px;background:rgba(20,17,15,.62);backdrop-filter:blur(7px)}.notice-dialog{position:relative;display:grid;grid-template-columns:minmax(180px,.8fr) minmax(260px,1.2fr);width:min(760px,100%);max-height:calc(100dvh - 44px);overflow:auto;border-radius:20px;background:#fff;box-shadow:0 28px 90px rgba(0,0,0,.28)}.notice-dialog>img{width:100%;height:100%;min-height:330px;object-fit:cover;background:#fff1ec}.notice-copy{display:grid;align-content:center;gap:12px;padding:42px}.notice-copy p{margin:0;color:#d95031;font-size:11px;font-weight:800;letter-spacing:.12em}.notice-copy h2{margin:0;font-size:30px;line-height:1.12}.notice-copy>span{color:#5f5a56;line-height:1.6}.notice-close{position:absolute;z-index:1;top:14px;right:14px;width:44px;height:44px;border:0;border-radius:50%;background:#fff;color:#222;font-size:26px;box-shadow:0 4px 18px #0002}.notice-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:8px}.notice-actions :is(a,button){display:inline-flex;align-items:center;justify-content:center;min-height:44px;padding:0 17px;border:1px solid #ddd;border-radius:10px;background:#fff;color:#222;font-weight:750;text-decoration:none}.notice-actions .notice-primary{border-color:#ff6846;background:#ff6846;color:#fff}.notice-dialog :is(a,button):focus-visible{outline:3px solid #9b301c;outline-offset:3px}@media(max-width:620px){.notice-dialog{grid-template-columns:1fr}.notice-dialog>img{min-height:180px;max-height:240px}.notice-copy{padding:28px 22px}.notice-copy h2{font-size:25px}}@media(prefers-reduced-motion:no-preference){.notice-dialog{animation:notice-in .18s ease-out}@keyframes notice-in{from{transform:translateY(14px);opacity:.7}to{transform:none;opacity:1}}}</style>
