SET NOCOUNT ON;
GO
IF DB_NAME() NOT IN (N'FastGuyDB',N'FastGuyDB_Inventory052_Test') THROW 51000,'052 validation target database is not approved',1;
IF OBJECT_ID(N'dbo.SchemaMigrationHistory',N'U') IS NULL OR NOT EXISTS(SELECT 1 FROM dbo.SchemaMigrationHistory WHERE migration_id = '052_ingredient_inventory_phase_1') THROW 51000,'052 validation failed: migration history missing',1;
IF EXISTS(SELECT 1 FROM (VALUES(N'InventoryItem'),(N'VariantInventoryItem'),(N'Recipe'),(N'RecipeItem'),(N'InventoryReservation'),(N'InventoryReservationItem'),(N'InventoryTransaction'),(N'InventoryReservationLegacyHistory')) x(name) WHERE OBJECT_ID(N'dbo.'+x.name,N'U') IS NULL) THROW 51000,'052 validation failed: required table missing',1;
IF COL_LENGTH('dbo.ProductVariant', 'inventory_mode') IS NULL THROW 51000, '052 validation failed: inventory_mode missing', 1;
IF COL_LENGTH(N'dbo.InventoryReservation',N'variant_id') IS NOT NULL OR COL_LENGTH(N'dbo.InventoryReservation',N'quantity') IS NOT NULL OR COL_LENGTH(N'dbo.InventoryTransaction',N'variant_id') IS NOT NULL THROW 51000,'052 validation failed: legacy column remains',1;
DECLARE @columns TABLE(table_name sysname,column_name sysname,type_name sysname,max_length smallint,precision tinyint,scale tinyint,is_nullable bit);
INSERT @columns VALUES
(N'ProductVariant',N'inventory_mode',N'varchar',20,0,0,0),
(N'InventoryItem',N'inventory_item_id',N'int',4,10,0,0),(N'InventoryItem',N'name',N'nvarchar',510,0,0,0),(N'InventoryItem',N'item_type',N'varchar',20,0,0,0),(N'InventoryItem',N'base_unit',N'varchar',10,0,0,0),(N'InventoryItem',N'on_hand_quantity',N'decimal',9,19,4,0),(N'InventoryItem',N'reserved_quantity',N'decimal',9,19,4,0),(N'InventoryItem',N'minimum_quantity',N'decimal',9,19,4,0),(N'InventoryItem',N'active',N'bit',1,1,0,0),(N'InventoryItem',N'created_at',N'datetime2',6,19,0,0),(N'InventoryItem',N'updated_at',N'datetime2',6,19,0,0),
(N'VariantInventoryItem',N'variant_inventory_item_id',N'int',4,10,0,0),(N'VariantInventoryItem',N'variant_id',N'int',4,10,0,0),(N'VariantInventoryItem',N'inventory_item_id',N'int',4,10,0,0),
(N'Recipe',N'recipe_id',N'int',4,10,0,0),(N'Recipe',N'variant_id',N'int',4,10,0,0),(N'Recipe',N'yield_quantity',N'decimal',9,19,4,0),(N'Recipe',N'active',N'bit',1,1,0,0),(N'Recipe',N'created_at',N'datetime2',6,19,0,0),(N'Recipe',N'updated_at',N'datetime2',6,19,0,0),
(N'RecipeItem',N'recipe_item_id',N'int',4,10,0,0),(N'RecipeItem',N'recipe_id',N'int',4,10,0,0),(N'RecipeItem',N'inventory_item_id',N'int',4,10,0,0),(N'RecipeItem',N'quantity',N'decimal',9,19,4,0),
(N'InventoryReservation',N'reservation_id',N'int',4,10,0,0),(N'InventoryReservation',N'order_id',N'int',4,10,0,0),(N'InventoryReservation',N'status',N'varchar',20,0,0,0),(N'InventoryReservation',N'created_at',N'datetime2',6,19,0,0),(N'InventoryReservation',N'updated_at',N'datetime2',6,19,0,0),
(N'InventoryReservationLegacyHistory',N'legacy_reservation_id',N'int',4,10,0,0),(N'InventoryReservationLegacyHistory',N'canonical_reservation_id',N'int',4,10,0,0),(N'InventoryReservationLegacyHistory',N'order_id',N'int',4,10,0,0),(N'InventoryReservationLegacyHistory',N'variant_id',N'int',4,10,0,0),(N'InventoryReservationLegacyHistory',N'inventory_item_id',N'int',4,10,0,0),(N'InventoryReservationLegacyHistory',N'quantity',N'decimal',9,19,4,0),(N'InventoryReservationLegacyHistory',N'status',N'varchar',20,0,0,0),(N'InventoryReservationLegacyHistory',N'created_at',N'datetime2',6,19,0,0),(N'InventoryReservationLegacyHistory',N'updated_at',N'datetime2',6,19,0,0),
(N'InventoryReservationItem',N'reservation_item_id',N'int',4,10,0,0),(N'InventoryReservationItem',N'reservation_id',N'int',4,10,0,0),(N'InventoryReservationItem',N'inventory_item_id',N'int',4,10,0,0),(N'InventoryReservationItem',N'quantity',N'decimal',9,19,4,0),
(N'InventoryTransaction',N'inventory_transaction_id',N'int',4,10,0,0),(N'InventoryTransaction',N'inventory_item_id',N'int',4,10,0,0),(N'InventoryTransaction',N'order_id',N'int',4,10,0,1),(N'InventoryTransaction',N'transaction_type',N'varchar',20,0,0,0),(N'InventoryTransaction',N'quantity',N'decimal',9,19,4,0),(N'InventoryTransaction',N'quantity_before',N'decimal',9,19,4,1),(N'InventoryTransaction',N'quantity_after',N'decimal',9,19,4,1),(N'InventoryTransaction',N'reference_type',N'varchar',30,0,0,1),(N'InventoryTransaction',N'reference_id',N'varchar',100,0,0,1),(N'InventoryTransaction',N'reason_code',N'varchar',50,0,0,1),(N'InventoryTransaction',N'note',N'nvarchar',1000,0,0,1),(N'InventoryTransaction',N'created_by',N'int',4,10,0,1),(N'InventoryTransaction',N'created_at',N'datetime2',6,19,0,0);
IF EXISTS(SELECT 1 FROM @columns e LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.'+e.table_name) AND c.name=e.column_name WHERE c.column_id IS NULL OR TYPE_NAME(c.user_type_id)<>e.type_name OR c.max_length<>e.max_length OR c.precision<>e.precision OR c.scale<>e.scale OR c.is_nullable<>e.is_nullable) THROW 51000,'052 validation failed: column definition mismatch',1;
IF EXISTS(SELECT table_name FROM @columns e WHERE e.table_name<>N'ProductVariant' GROUP BY table_name HAVING COUNT(*)<>(SELECT COUNT(*) FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.'+table_name))) THROW 51000,'052 validation failed: unexpected column',1;
DECLARE @defaults TABLE(table_name sysname,column_name sysname,constraint_name sysname,token nvarchar(50)); INSERT @defaults VALUES (N'ProductVariant',N'inventory_mode',N'DF_ProductVariant_InventoryMode',N'UNTRACKED'),(N'InventoryItem',N'on_hand_quantity',N'DF_InventoryItem_OnHand',N'0'),(N'InventoryItem',N'reserved_quantity',N'DF_InventoryItem_Reserved',N'0'),(N'InventoryItem',N'minimum_quantity',N'DF_InventoryItem_Minimum',N'0'),(N'InventoryItem',N'active',N'DF_InventoryItem_Active',N'1'),(N'InventoryItem',N'created_at',N'DF_InventoryItem_Created',N'getdate'),(N'InventoryItem',N'updated_at',N'DF_InventoryItem_Updated',N'getdate'),(N'Recipe',N'yield_quantity',N'DF_Recipe_Yield',N'1'),(N'Recipe',N'active',N'DF_Recipe_Active',N'1'),(N'Recipe',N'created_at',N'DF_Recipe_Created',N'getdate'),(N'Recipe',N'updated_at',N'DF_Recipe_Updated',N'getdate');
IF EXISTS(SELECT 1 FROM @defaults e LEFT JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.'+e.table_name) AND c.name=e.column_name LEFT JOIN sys.default_constraints dc ON dc.parent_object_id=c.object_id AND dc.parent_column_id=c.column_id AND dc.name=e.constraint_name WHERE dc.object_id IS NULL OR LOWER(dc.definition) NOT LIKE N'%'+LOWER(e.token)+N'%') THROW 51000,'052 validation failed: default mismatch',1;
DECLARE @no_defaults TABLE(table_name sysname,column_name sysname); INSERT @no_defaults VALUES(N'InventoryTransaction',N'transaction_type');
IF EXISTS(SELECT 1 FROM @no_defaults e JOIN sys.columns c ON c.object_id=OBJECT_ID(N'dbo.'+e.table_name) AND c.name=e.column_name JOIN sys.default_constraints dc ON dc.parent_object_id=c.object_id AND dc.parent_column_id=c.column_id) THROW 51000,'052 validation failed: unexpected default',1;
DECLARE @checks TABLE(table_name sysname,name sysname,token nvarchar(100)); INSERT @checks VALUES (N'ProductVariant',N'CK_ProductVariant_InventoryMode',N'ingredient'),(N'InventoryItem',N'CK_InventoryItem_Type',N'finished_good'),(N'InventoryItem',N'CK_InventoryItem_BaseUnit',N'piece'),(N'InventoryItem',N'CK_InventoryItem_OnHand',N'>=0'),(N'InventoryItem',N'CK_InventoryItem_Reserved',N'<=on_hand_quantity'),(N'InventoryItem',N'CK_InventoryItem_Minimum',N'>=0'),(N'Recipe',N'CK_Recipe_Yield',N'>0'),(N'RecipeItem',N'CK_RecipeItem_Quantity',N'>0'),(N'InventoryReservation',N'CK_InventoryReservation_Status',N'wasted'),(N'InventoryReservationItem',N'CK_InventoryReservationItem_Quantity',N'>0'),(N'InventoryTransaction',N'CK_InventoryTransaction_Quantity',N'<>0'),(N'InventoryTransaction',N'CK_InventoryTransaction_Type',N'return');
IF EXISTS(SELECT 1 FROM @checks e LEFT JOIN sys.check_constraints cc ON cc.parent_object_id=OBJECT_ID(N'dbo.'+e.table_name) AND cc.name=e.name WHERE cc.object_id IS NULL OR cc.is_disabled=1 OR cc.is_not_trusted=1 OR LOWER(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(cc.definition,N'[',N''),N']',N''),N'(',N''),N')',N''),N' ',N'')) NOT LIKE N'%'+e.token+N'%') THROW 51000,'052 validation failed: check mismatch',1;
DECLARE @fks TABLE(name sysname NULL,parent_table sysname,parent_column sysname,reference_table sysname,reference_column sysname); INSERT @fks VALUES (N'FK_VariantInventoryItem_Variant',N'VariantInventoryItem',N'variant_id',N'ProductVariant',N'variant_id'),(N'FK_VariantInventoryItem_Item',N'VariantInventoryItem',N'inventory_item_id',N'InventoryItem',N'inventory_item_id'),(N'FK_Recipe_Variant',N'Recipe',N'variant_id',N'ProductVariant',N'variant_id'),(N'FK_RecipeItem_Recipe',N'RecipeItem',N'recipe_id',N'Recipe',N'recipe_id'),(N'FK_RecipeItem_Item',N'RecipeItem',N'inventory_item_id',N'InventoryItem',N'inventory_item_id'),(N'FK_InventoryReservationItem_Reservation',N'InventoryReservationItem',N'reservation_id',N'InventoryReservation',N'reservation_id'),(N'FK_InventoryReservationItem_Item',N'InventoryReservationItem',N'inventory_item_id',N'InventoryItem',N'inventory_item_id'),(N'FK_InventoryTransaction_Item',N'InventoryTransaction',N'inventory_item_id',N'InventoryItem',N'inventory_item_id'),(NULL,N'InventoryReservation',N'order_id',N'Orders',N'order_id'),(NULL,N'InventoryTransaction',N'order_id',N'Orders',N'order_id'),(NULL,N'InventoryTransaction',N'created_by',N'Users',N'user_id'),(N'FK_InventoryReservationLegacyHistory_Item',N'InventoryReservationLegacyHistory',N'inventory_item_id',N'InventoryItem',N'inventory_item_id');
IF EXISTS(SELECT 1 FROM @fks e LEFT JOIN sys.foreign_keys fk ON fk.parent_object_id=OBJECT_ID(N'dbo.'+e.parent_table) AND fk.referenced_object_id=OBJECT_ID(N'dbo.'+e.reference_table) AND (e.name IS NULL OR fk.name=e.name) LEFT JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id=fk.object_id LEFT JOIN sys.columns pc ON pc.object_id=fkc.parent_object_id AND pc.column_id=fkc.parent_column_id LEFT JOIN sys.columns rc ON rc.object_id=fkc.referenced_object_id AND rc.column_id=fkc.referenced_column_id WHERE fk.object_id IS NULL OR fk.is_disabled=1 OR fk.is_not_trusted=1 OR pc.name<>e.parent_column OR rc.name<>e.reference_column OR (SELECT COUNT(*) FROM sys.foreign_key_columns x WHERE x.constraint_object_id=fk.object_id)<>1) THROW 51000,'052 validation failed: foreign key mismatch',1;
DECLARE @indexes TABLE(table_name sysname,name sysname,is_unique bit,keys nvarchar(200)); INSERT @indexes VALUES (N'VariantInventoryItem',N'UQ_VariantInventoryItem_Variant',1,N'variant_id'),(N'VariantInventoryItem',N'UQ_VariantInventoryItem_Item',1,N'inventory_item_id'),(N'Recipe',N'UQ_Recipe_Variant',1,N'variant_id'),(N'RecipeItem',N'UQ_RecipeItem_RecipeInventoryItem',1,N'recipe_id,inventory_item_id'),(N'InventoryReservation',N'UQ_InventoryReservation_Order',1,N'order_id'),(N'InventoryReservationItem',N'UQ_InventoryReservationItem_ReservationInventoryItem',1,N'reservation_id,inventory_item_id'),(N'InventoryItem',N'IX_InventoryItem_ActiveType',0,N'active,item_type'),(N'RecipeItem',N'IX_RecipeItem_InventoryItem',0,N'inventory_item_id'),(N'InventoryReservationItem',N'IX_InventoryReservationItem_InventoryItem',0,N'inventory_item_id'),(N'InventoryTransaction',N'IX_InventoryTransaction_Order',0,N'order_id'),(N'InventoryTransaction',N'IX_InventoryTransaction_ItemCreated',0,N'inventory_item_id,created_at');
IF EXISTS(SELECT 1 FROM @indexes e LEFT JOIN sys.indexes i ON i.object_id=OBJECT_ID(N'dbo.'+e.table_name) AND i.name=e.name OUTER APPLY(SELECT STRING_AGG(c.name,N',') WITHIN GROUP(ORDER BY ic.key_ordinal) keys FROM sys.index_columns ic JOIN sys.columns c ON c.object_id=ic.object_id AND c.column_id=ic.column_id WHERE ic.object_id=i.object_id AND ic.index_id=i.index_id AND ic.key_ordinal>0) actual WHERE i.index_id IS NULL OR i.is_disabled=1 OR i.is_unique<>e.is_unique OR actual.keys<>e.keys) THROW 51000,'052 validation failed: index mismatch',1;
IF EXISTS(SELECT 1 FROM dbo.InventoryItem WHERE on_hand_quantity<0 OR reserved_quantity<0 OR reserved_quantity>on_hand_quantity OR minimum_quantity<0) THROW 51000,'052 validation failed: invalid inventory balance',1;
IF EXISTS(SELECT 1 FROM dbo.ProductVariant WHERE inventory_mode NOT IN('INGREDIENT','FINISHED_GOOD','UNTRACKED','SUSPENDED')) THROW 51000,'052 validation failed: invalid inventory mode',1;
IF EXISTS(SELECT 1 FROM dbo.ProductVariant v WHERE v.quantity_available IS NOT NULL AND ((v.status='AVAILABLE' AND v.inventory_mode<>'FINISHED_GOOD') OR (SELECT COUNT(*) FROM dbo.VariantInventoryItem m WHERE m.variant_id=v.variant_id)<>1 OR NOT EXISTS(SELECT 1 FROM dbo.VariantInventoryItem m JOIN dbo.InventoryItem i ON i.inventory_item_id=m.inventory_item_id WHERE m.variant_id=v.variant_id AND i.item_type='FINISHED_GOOD' AND i.base_unit='PIECE' AND i.on_hand_quantity-i.reserved_quantity=CONVERT(decimal(19,4),v.quantity_available)))) THROW 51000,'052 validation failed: finished-good backfill mismatch',1;
IF EXISTS(SELECT 1 FROM dbo.InventoryItem i OUTER APPLY(SELECT COALESCE(SUM(ri.quantity),0) reserved_quantity FROM dbo.InventoryReservationItem ri JOIN dbo.InventoryReservation r ON r.reservation_id=ri.reservation_id WHERE ri.inventory_item_id=i.inventory_item_id AND r.status='RESERVED') expected WHERE i.reserved_quantity<>expected.reserved_quantity) THROW 51000,'052 validation failed: reserved balance mismatch',1;
IF EXISTS(SELECT 1 FROM (SELECT h.*,MIN(h.legacy_reservation_id) OVER(PARTITION BY h.order_id) expected_canonical_reservation_id FROM dbo.InventoryReservationLegacyHistory h) h LEFT JOIN dbo.VariantInventoryItem m ON m.variant_id=h.variant_id WHERE h.legacy_reservation_id IS NULL OR h.canonical_reservation_id IS NULL OR h.order_id IS NULL OR h.variant_id IS NULL OR h.inventory_item_id IS NULL OR h.quantity<=0 OR h.status NOT IN('RESERVED','CONSUMED','RELEASED','WASTED') OR h.created_at IS NULL OR h.updated_at IS NULL OR m.inventory_item_id<>h.inventory_item_id OR h.canonical_reservation_id<>h.expected_canonical_reservation_id) THROW 51000,'052 validation failed: legacy reservation history mismatch',1;
IF EXISTS(SELECT 1 FROM dbo.InventoryReservationItem ri OUTER APPLY(SELECT SUM(h.quantity) quantity FROM dbo.InventoryReservationLegacyHistory h WHERE h.canonical_reservation_id=ri.reservation_id AND h.inventory_item_id=ri.inventory_item_id) expected WHERE expected.quantity IS NULL OR ri.quantity<>expected.quantity) OR EXISTS(SELECT 1 FROM dbo.InventoryReservationLegacyHistory h GROUP BY h.canonical_reservation_id,h.inventory_item_id HAVING SUM(h.quantity)<>(SELECT ri.quantity FROM dbo.InventoryReservationItem ri WHERE ri.reservation_id=h.canonical_reservation_id AND ri.inventory_item_id=h.inventory_item_id)) THROW 51000,'052 validation failed: legacy reservation content mismatch',1;
IF EXISTS(SELECT 1 FROM dbo.InventoryReservationLegacyHistory h GROUP BY h.order_id HAVING COUNT(DISTINCT h.status)>1) OR EXISTS(SELECT 1 FROM dbo.InventoryReservation r JOIN dbo.InventoryReservationLegacyHistory h ON h.canonical_reservation_id=r.reservation_id GROUP BY r.reservation_id,r.status HAVING r.status<>MIN(h.status)) THROW 51000,'052 validation failed: reservation status reconciliation mismatch',1;
IF EXISTS(SELECT 1 FROM dbo.InventoryReservation r LEFT JOIN dbo.InventoryReservationItem ri ON ri.reservation_id=r.reservation_id WHERE ri.reservation_id IS NULL) OR EXISTS(SELECT 1 FROM dbo.InventoryTransaction WHERE inventory_item_id IS NULL) THROW 51000,'052 validation failed: conversion missing',1;
PRINT '052 validation passed';
GO
