SET NOCOUNT ON;
SET XACT_ABORT ON;
IF DB_NAME() NOT IN (N'FastGuyDB',N'FastGuyDB_Inventory053_Test') THROW 51000, '053 validator target database is not approved', 1;
IF OBJECT_ID(N'dbo.SchemaMigrationHistory',N'U') IS NULL OR NOT EXISTS(SELECT 1 FROM dbo.SchemaMigrationHistory WHERE migration_id='053_inventory_costing_stock_count') THROW 51000, '053 migration history missing', 1;

DECLARE @columns TABLE(table_name sysname,column_name sysname,type_name sysname,max_length smallint,precision tinyint,scale tinyint,is_nullable bit);
INSERT @columns VALUES
('InventoryItem','inventory_code','varchar',30,0,0,0),('InventoryItem','count_frequency','varchar',10,0,0,0),('InventoryItem','average_unit_cost','decimal',9,19,4,0),('InventoryItem','last_counted_at','datetime2',6,19,0,1),
('GoodsReceipt','goods_receipt_id','int',4,10,0,0),('GoodsReceipt','supplier_name','nvarchar',300,0,0,0),('GoodsReceipt','invoice_number','nvarchar',200,0,0,1),('GoodsReceipt','received_at','datetime2',6,19,0,0),('GoodsReceipt','status','varchar',10,0,0,0),('GoodsReceipt','created_by','int',4,10,0,0),('GoodsReceipt','approved_by','int',4,10,0,1),('GoodsReceipt','created_at','datetime2',6,19,0,0),('GoodsReceipt','approved_at','datetime2',6,19,0,1),
('GoodsReceiptItem','goods_receipt_item_id','int',4,10,0,0),('GoodsReceiptItem','goods_receipt_id','int',4,10,0,0),('GoodsReceiptItem','inventory_item_id','int',4,10,0,0),('GoodsReceiptItem','purchase_quantity','decimal',9,19,4,0),('GoodsReceiptItem','purchase_unit','nvarchar',60,0,0,0),('GoodsReceiptItem','conversion_factor','decimal',9,19,4,0),('GoodsReceiptItem','base_quantity','decimal',9,19,4,0),('GoodsReceiptItem','purchase_unit_price','decimal',9,19,4,0),('GoodsReceiptItem','line_total','decimal',9,19,4,0),('GoodsReceiptItem','average_cost_before','decimal',9,19,4,1),('GoodsReceiptItem','average_cost_after','decimal',9,19,4,1),
('StockCount','stock_count_id','int',4,10,0,0),('StockCount','count_date','date',3,10,0,0),('StockCount','frequency','varchar',10,0,0,0),('StockCount','status','varchar',10,0,0,0),('StockCount','created_by','int',4,10,0,0),('StockCount','approved_by','int',4,10,0,1),('StockCount','created_at','datetime2',6,19,0,0),('StockCount','approved_at','datetime2',6,19,0,1),
('StockCountItem','stock_count_item_id','int',4,10,0,0),('StockCountItem','stock_count_id','int',4,10,0,0),('StockCountItem','inventory_item_id','int',4,10,0,0),('StockCountItem','theoretical_quantity','decimal',9,19,4,0),('StockCountItem','actual_quantity','decimal',9,19,4,1),('StockCountItem','variance_quantity','decimal',9,19,4,1),('StockCountItem','unit_cost_snapshot','decimal',9,19,4,1),('StockCountItem','variance_cost','decimal',9,19,4,1),('StockCountItem','reason_code','varchar',50,0,0,1),('StockCountItem','note','nvarchar',1000,0,0,1),
('InventoryTransaction','unit_cost_snapshot','decimal',9,19,4,1),('InventoryTransaction','total_cost','decimal',9,19,4,1),('InventoryTransaction','goods_receipt_id','int',4,10,0,1),('InventoryTransaction','stock_count_id','int',4,10,0,1);
IF EXISTS(SELECT 1 FROM @columns e LEFT JOIN sys.tables t ON t.name=e.table_name AND SCHEMA_NAME(t.schema_id)='dbo' LEFT JOIN sys.columns c ON c.object_id=t.object_id AND c.name=e.column_name LEFT JOIN sys.types ty ON ty.user_type_id=c.user_type_id WHERE c.column_id IS NULL OR ty.name<>e.type_name OR c.max_length<>e.max_length OR c.precision<>e.precision OR c.scale<>e.scale OR c.is_nullable<>e.is_nullable) THROW 51000, '053 column type, nullability, or precision mismatch', 1;

DECLARE @defaults TABLE(table_name sysname,column_name sysname,constraint_name sysname,definition nvarchar(100));
INSERT @defaults VALUES ('InventoryItem','count_frequency','DF_InventoryItem_CountFrequency','(''WEEKLY'')'),('InventoryItem','average_unit_cost','DF_InventoryItem_AverageUnitCost','((0))'),('GoodsReceipt','status','DF_GoodsReceipt_Status','(''DRAFT'')'),('GoodsReceipt','created_at','DF_GoodsReceipt_CreatedAt','(getdate())'),('StockCount','status','DF_StockCount_Status','(''DRAFT'')'),('StockCount','created_at','DF_StockCount_CreatedAt','(getdate())');
IF EXISTS(SELECT 1 FROM @defaults e LEFT JOIN sys.tables t ON t.name=e.table_name AND SCHEMA_NAME(t.schema_id)='dbo' LEFT JOIN sys.columns c ON c.object_id=t.object_id AND c.name=e.column_name LEFT JOIN sys.default_constraints d ON d.parent_object_id=t.object_id AND d.parent_column_id=c.column_id AND d.name=e.constraint_name WHERE d.object_id IS NULL OR LOWER(REPLACE(d.definition,' ',''))<>LOWER(e.definition)) THROW 51000, '053 default mismatch', 1;

DECLARE @fks TABLE(name sysname,parent_table sysname,parent_column sysname,referenced_table sysname,referenced_column sysname);
INSERT @fks VALUES ('FK_GoodsReceipt_CreatedBy','GoodsReceipt','created_by','Users','user_id'),('FK_GoodsReceipt_ApprovedBy','GoodsReceipt','approved_by','Users','user_id'),('FK_GoodsReceiptItem_Receipt','GoodsReceiptItem','goods_receipt_id','GoodsReceipt','goods_receipt_id'),('FK_GoodsReceiptItem_Item','GoodsReceiptItem','inventory_item_id','InventoryItem','inventory_item_id'),('FK_StockCount_CreatedBy','StockCount','created_by','Users','user_id'),('FK_StockCount_ApprovedBy','StockCount','approved_by','Users','user_id'),('FK_StockCountItem_Count','StockCountItem','stock_count_id','StockCount','stock_count_id'),('FK_StockCountItem_Item','StockCountItem','inventory_item_id','InventoryItem','inventory_item_id'),('FK_InventoryTransaction_GoodsReceipt','InventoryTransaction','goods_receipt_id','GoodsReceipt','goods_receipt_id'),('FK_InventoryTransaction_StockCount','InventoryTransaction','stock_count_id','StockCount','stock_count_id');
IF EXISTS(SELECT 1 FROM @fks e WHERE NOT EXISTS(SELECT 1 FROM sys.foreign_keys fk JOIN sys.foreign_key_columns fkc ON fkc.constraint_object_id=fk.object_id JOIN sys.tables pt ON pt.object_id=fk.parent_object_id JOIN sys.columns pc ON pc.object_id=pt.object_id AND pc.column_id=fkc.parent_column_id JOIN sys.tables rt ON rt.object_id=fk.referenced_object_id JOIN sys.columns rc ON rc.object_id=rt.object_id AND rc.column_id=fkc.referenced_column_id WHERE fk.name=e.name AND pt.name=e.parent_table AND pc.name=e.parent_column AND rt.name=e.referenced_table AND rc.name=e.referenced_column AND fk.is_disabled=0 AND fk.is_not_trusted=0)) THROW 51000, '053 foreign key missing or invalid', 1;

DECLARE @constraints TABLE(table_name sysname,name sysname,type char(1));
INSERT @constraints VALUES ('GoodsReceipt','PK_GoodsReceipt','P'),('GoodsReceiptItem','PK_GoodsReceiptItem','P'),('StockCount','PK_StockCount','P'),('StockCountItem','PK_StockCountItem','P'),('InventoryItem','UQ_InventoryItem_Code','U'),('GoodsReceiptItem','UQ_GoodsReceiptItem_ReceiptItem','U'),('StockCountItem','UQ_StockCountItem_CountItem','U'),('InventoryItem','CK_InventoryItem_CountFrequency','C'),('InventoryItem','CK_InventoryItem_AverageUnitCost','C'),('GoodsReceipt','CK_GoodsReceipt_Status','C'),('GoodsReceipt','CK_GoodsReceipt_Approval','C'),('GoodsReceiptItem','CK_GoodsReceiptItem_Positive','C'),('GoodsReceiptItem','CK_GoodsReceiptItem_Cost','C'),('StockCount','CK_StockCount_Frequency','C'),('StockCount','CK_StockCount_Status','C'),('StockCount','CK_StockCount_Approval','C'),('StockCountItem','CK_StockCountItem_Quantity','C'),('StockCountItem','CK_StockCountItem_Cost','C'),('InventoryTransaction','CK_InventoryTransaction_Cost','C');
IF EXISTS(SELECT 1 FROM @constraints e JOIN sys.tables t ON t.name=e.table_name AND SCHEMA_NAME(t.schema_id)='dbo' WHERE (e.type='P' AND NOT EXISTS(SELECT 1 FROM sys.key_constraints k WHERE k.parent_object_id=t.object_id AND k.name=e.name AND k.type='PK')) OR (e.type='U' AND NOT EXISTS(SELECT 1 FROM sys.key_constraints k WHERE k.parent_object_id=t.object_id AND k.name=e.name AND k.type='UQ')) OR (e.type='C' AND NOT EXISTS(SELECT 1 FROM sys.check_constraints c WHERE c.parent_object_id=t.object_id AND c.name=e.name AND c.is_disabled=0 AND c.is_not_trusted=0))) THROW 51000, '053 primary key, unique, or check constraint missing or invalid', 1;
DECLARE @checks TABLE(name sysname,definition nvarchar(1000));
INSERT @checks VALUES ('CK_InventoryItem_CountFrequency','[count_frequency]=''WEEKLY''OR[count_frequency]=''DAILY'''),('CK_InventoryItem_AverageUnitCost','[average_unit_cost]>=(0)'),('CK_GoodsReceipt_Status','[status]=''APPROVED''OR[status]=''DRAFT'''),('CK_GoodsReceipt_Approval','[status]=''DRAFT''AND[approved_by]ISNULLAND[approved_at]ISNULLOR[status]=''APPROVED''AND[approved_by]ISNOTNULLAND[approved_at]ISNOTNULL'),('CK_GoodsReceiptItem_Positive','[purchase_quantity]>(0)AND[conversion_factor]>(0)AND[base_quantity]>(0)AND[purchase_unit_price]>(0)AND[line_total]>(0)'),('CK_GoodsReceiptItem_Cost','[average_cost_before]ISNULLAND[average_cost_after]ISNULLOR[average_cost_before]>=(0)AND[average_cost_after]>=(0)'),('CK_StockCount_Frequency','[frequency]=''WEEKLY''OR[frequency]=''DAILY'''),('CK_StockCount_Status','[status]=''APPROVED''OR[status]=''DRAFT'''),('CK_StockCount_Approval','[status]=''DRAFT''AND[approved_by]ISNULLAND[approved_at]ISNULLOR[status]=''APPROVED''AND[approved_by]ISNOTNULLAND[approved_at]ISNOTNULL'),('CK_StockCountItem_Quantity','[theoretical_quantity]>=(0)AND[actual_quantity]ISNULLOR[actual_quantity]>=(0)'),('CK_StockCountItem_Cost','[unit_cost_snapshot]ISNULLOR[unit_cost_snapshot]>=(0)'),('CK_InventoryTransaction_Cost','[unit_cost_snapshot]ISNULLOR[unit_cost_snapshot]>=(0)AND[total_cost]ISNULLOR[total_cost]>=(0)');
IF EXISTS(SELECT 1 FROM @checks e JOIN sys.check_constraints c ON c.name=e.name WHERE REPLACE(REPLACE(REPLACE(c.definition,' ',''),'(',''),')','')<>REPLACE(REPLACE(e.definition,'(',''),')','')) THROW 51000, '053 check definition mismatch', 1;
DECLARE @keys TABLE(table_name sysname,name sysname,column_1 sysname,column_2 sysname NULL);
INSERT @keys VALUES ('GoodsReceipt','PK_GoodsReceipt','goods_receipt_id',NULL),('GoodsReceiptItem','PK_GoodsReceiptItem','goods_receipt_item_id',NULL),('StockCount','PK_StockCount','stock_count_id',NULL),('StockCountItem','PK_StockCountItem','stock_count_item_id',NULL),('InventoryItem','UQ_InventoryItem_Code','inventory_code',NULL),('GoodsReceiptItem','UQ_GoodsReceiptItem_ReceiptItem','goods_receipt_id','inventory_item_id'),('StockCountItem','UQ_StockCountItem_CountItem','stock_count_id','inventory_item_id');
IF EXISTS(SELECT 1 FROM @keys e WHERE NOT EXISTS(SELECT 1 FROM sys.key_constraints k JOIN sys.tables t ON t.object_id=k.parent_object_id JOIN sys.index_columns ic1 ON ic1.object_id=t.object_id AND ic1.index_id=k.unique_index_id AND ic1.key_ordinal=1 JOIN sys.columns c1 ON c1.object_id=t.object_id AND c1.column_id=ic1.column_id LEFT JOIN sys.index_columns ic2 ON ic2.object_id=t.object_id AND ic2.index_id=k.unique_index_id AND ic2.key_ordinal=2 LEFT JOIN sys.columns c2 ON c2.object_id=t.object_id AND c2.column_id=ic2.column_id WHERE t.name=e.table_name AND SCHEMA_NAME(t.schema_id)='dbo' AND k.name=e.name AND c1.name=e.column_1 AND ISNULL(c2.name,'')=ISNULL(e.column_2,''))) THROW 51000, '053 primary key or unique columns invalid', 1;

IF NOT EXISTS(SELECT 1 FROM sys.indexes i JOIN sys.index_columns ic1 ON ic1.object_id=i.object_id AND ic1.index_id=i.index_id AND ic1.key_ordinal=1 JOIN sys.columns c1 ON c1.object_id=i.object_id AND c1.column_id=ic1.column_id JOIN sys.index_columns ic2 ON ic2.object_id=i.object_id AND ic2.index_id=i.index_id AND ic2.key_ordinal=2 JOIN sys.columns c2 ON c2.object_id=i.object_id AND c2.column_id=ic2.column_id WHERE i.object_id=OBJECT_ID(N'dbo.GoodsReceipt') AND i.name=N'IX_GoodsReceipt_StatusReceived' AND c1.name='status' AND c2.name='received_at' AND ic2.is_descending_key=1) THROW 51000, '053 goods receipt index invalid', 1;
IF NOT EXISTS(SELECT 1 FROM sys.indexes i JOIN sys.index_columns ic1 ON ic1.object_id=i.object_id AND ic1.index_id=i.index_id AND ic1.key_ordinal=1 JOIN sys.columns c1 ON c1.object_id=i.object_id AND c1.column_id=ic1.column_id JOIN sys.index_columns ic2 ON ic2.object_id=i.object_id AND ic2.index_id=i.index_id AND ic2.key_ordinal=2 JOIN sys.columns c2 ON c2.object_id=i.object_id AND c2.column_id=ic2.column_id WHERE i.object_id=OBJECT_ID(N'dbo.StockCount') AND i.name=N'IX_StockCount_StatusDate' AND c1.name='status' AND c2.name='count_date' AND ic2.is_descending_key=1) THROW 51000, '053 stock count index invalid', 1;
IF NOT EXISTS(SELECT 1 FROM sys.indexes i JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id AND ic.key_ordinal=1 JOIN sys.columns c ON c.object_id=i.object_id AND c.column_id=ic.column_id WHERE i.object_id=OBJECT_ID(N'dbo.InventoryTransaction') AND i.name=N'IX_InventoryTransaction_GoodsReceipt' AND c.name='goods_receipt_id' AND REPLACE(REPLACE(REPLACE(i.filter_definition,' ',''),'(',''),')','')='[goods_receipt_id]ISNOTNULL') THROW 51000, '053 goods receipt filtered index invalid', 1;
IF NOT EXISTS(SELECT 1 FROM sys.indexes i JOIN sys.index_columns ic ON ic.object_id=i.object_id AND ic.index_id=i.index_id AND ic.key_ordinal=1 JOIN sys.columns c ON c.object_id=i.object_id AND c.column_id=ic.column_id WHERE i.object_id=OBJECT_ID(N'dbo.InventoryTransaction') AND i.name=N'IX_InventoryTransaction_StockCount' AND c.name='stock_count_id' AND REPLACE(REPLACE(REPLACE(i.filter_definition,' ',''),'(',''),')','')='[stock_count_id]ISNOTNULL') THROW 51000, '053 stock count filtered index invalid', 1;

IF EXISTS(SELECT 1 FROM dbo.InventoryItem WHERE inventory_code IS NULL OR inventory_code='' OR count_frequency NOT IN('DAILY','WEEKLY') OR average_unit_cost<0) THROW 51000, '053 inventory data invalid', 1;
IF EXISTS(SELECT inventory_item_id FROM dbo.InventoryTransaction WHERE reference_type='MIGRATION' AND reference_id='053' GROUP BY inventory_item_id HAVING COUNT_BIG(*)>1) OR EXISTS(SELECT 1 FROM dbo.InventoryTransaction WHERE reference_type='MIGRATION' AND reference_id='053' AND (transaction_type<>'ADJUSTMENT' OR quantity_before<>0 OR quantity_after<>quantity OR unit_cost_snapshot<>0 OR total_cost<>0)) THROW 51000, '053 opening balance ledger invalid', 1;
PRINT '053 validation passed';
