SET NOCOUNT ON;
SET XACT_ABORT ON;
IF DB_NAME() NOT IN (N'FastGuyDB',N'FastGuyDB_Operations060_Test') THROW 51000, '059 validator target database is not approved', 1;
IF OBJECT_ID(N'dbo.SchemaMigrationHistory',N'U') IS NULL OR NOT EXISTS(SELECT 1 FROM dbo.SchemaMigrationHistory WHERE migration_id='059_shift_schedule_order_timeout') THROW 51000, '059 migration history missing', 1;
IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.WorkShift') AND name=N'shift_code' AND is_nullable=0) THROW 51000, '059 shift_code mismatch', 1;
IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.WorkShift') AND name=N'check_in_source' AND is_nullable=1) THROW 51000, '059 check_in_source mismatch', 1;
IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.WorkShift') AND name=N'check_out_source' AND is_nullable=1) THROW 51000, '059 check_out_source mismatch', 1;
IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.WorkShift') AND name=N'staff_role_snapshot' AND is_nullable=0) THROW 51000, '059 staff_role_snapshot mismatch', 1;
IF NOT EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.WorkShift') AND name=N'DF_WorkShift_StaffRoleSnapshot') THROW 51000, '059 role snapshot default missing', 1;
IF NOT EXISTS(SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.WorkShift') AND name=N'CK_WorkShift_Time' AND is_disabled=0 AND is_not_trusted=0 AND definition NOT LIKE N'% OR %') THROW 51000, '059 same-day time check missing', 1;
IF NOT EXISTS(SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.WorkShift') AND name=N'CK_WorkShift_ShiftCode' AND is_disabled=0 AND is_not_trusted=0) THROW 51000, '059 shift code check missing', 1;
IF NOT EXISTS(SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.WorkShift') AND name IN (N'CK_WorkShift_CheckInSource',N'CK_WorkShift_CheckOutSource') AND is_disabled=0 AND is_not_trusted=0 HAVING COUNT(*)=2) THROW 51000, '059 MANUAL/AUTO checks missing', 1;
IF NOT EXISTS(SELECT 1 FROM sys.check_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.WorkShift') AND name=N'CK_WorkShift_StaffFixedTimes' AND is_disabled=0 AND is_not_trusted=0) THROW 51000, '059 fixed STAFF times check missing', 1;
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.WorkShift') AND name=N'UX_WorkShift_Staff_Date_Code' AND is_unique=1 AND has_filter=1 AND filter_definition LIKE N'%staff_role_snapshot%STAFF%' AND is_disabled=0) THROW 51000, '059 UX_WorkShift_Staff_Date_Code missing', 1;
IF EXISTS(SELECT 1 FROM sys.triggers WHERE parent_id=OBJECT_ID(N'dbo.WorkShift') AND name IN (N'TR_WorkShift_RoleGuard',N'TR_WorkShift_RoleSnapshot')) THROW 51000, '059 WorkShift role triggers must be absent', 1;
IF NOT EXISTS(SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID(N'dbo.Orders') AND name=N'status_entered_at' AND is_nullable=0) THROW 51000, '059 status_entered_at mismatch', 1;
IF NOT EXISTS(SELECT 1 FROM sys.default_constraints WHERE parent_object_id=OBJECT_ID(N'dbo.Orders') AND name=N'DF_Orders_StatusEnteredAt') THROW 51000, '059 status timestamp default missing', 1;
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.Orders') AND name=N'IX_Orders_Status_StatusEnteredAt' AND is_disabled=0) THROW 51000, '059 IX_Orders_Status_StatusEnteredAt missing', 1;
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.Orders') AND name=N'IX_Orders_StaffShift_Status' AND is_disabled=0) THROW 51000, '059 IX_Orders_StaffShift_Status missing', 1;
IF NOT EXISTS(SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID(N'dbo.Orders') AND name=N'IX_Orders_PaymentStatus_OrderStatus_StatusEnteredAt' AND is_disabled=0) THROW 51000, '059 IX_Orders_PaymentStatus_OrderStatus_StatusEnteredAt missing', 1;
IF EXISTS(SELECT 1 FROM dbo.WorkShift WHERE shift_code NOT IN ('MORNING','AFTERNOON','EVENING') OR staff_role_snapshot NOT IN ('STAFF','LEGACY_STAFF','NON_STAFF') OR check_in_source NOT IN ('MANUAL','AUTO') OR check_out_source NOT IN ('MANUAL','AUTO')) THROW 51000, '059 invalid shift data', 1;
IF EXISTS(SELECT 1 FROM dbo.WorkShift WHERE start_time>=end_time) THROW 51000, '059 overnight or invalid shift time', 1;
IF EXISTS(SELECT 1 FROM dbo.WorkShift WHERE staff_role_snapshot='STAFF' AND NOT ((shift_code='MORNING' AND start_time='08:00' AND end_time='12:00') OR (shift_code='AFTERNOON' AND start_time='12:00' AND end_time='16:00') OR (shift_code='EVENING' AND start_time='16:00' AND end_time='21:00'))) THROW 51000, '059 invalid STAFF fixed times', 1;
IF EXISTS(SELECT shift_date,shift_code FROM dbo.WorkShift WHERE staff_role_snapshot='STAFF' GROUP BY shift_date,shift_code HAVING COUNT_BIG(*)>1) THROW 51000, '059 duplicate STAFF shifts', 1;
IF EXISTS(SELECT 1 FROM dbo.Orders WHERE status_entered_at IS NULL) THROW 51000, '059 invalid order timeout data', 1;
PRINT '059 validation passed';
