package dao;

import utils.DatabaseUtil;
import jakarta.persistence.*;
import java.time.*;
import java.util.*;

public class InventoryTransactionDAO {
    static List<String> buildConditions(Integer inventoryItemId,Integer orderId,String type,LocalDateTime from,LocalDateTime to){List<String>c=new ArrayList<>();if(inventoryItemId!=null)c.add("t.inventoryItem.inventoryItemId = :inventoryItemId");if(orderId!=null)c.add("t.order.orderId = :orderId");if(type!=null&&!type.isBlank())c.add("t.transactionType = :transactionType");if(from!=null)c.add("t.createdAt >= :fromDate");if(to!=null)c.add("t.createdAt < :toDate");return c;}
    static String where(List<String>c){return c.isEmpty()?"":" WHERE "+String.join(" AND ",c);}
    static int firstResult(int page,int size){try{return Math.multiplyExact(page,size);}catch(ArithmeticException e){throw new IllegalArgumentException("Pagination offset too large");}}
    static LocalDateTime toEnd(LocalDate d){return LocalDate.MAX.equals(d)?LocalDateTime.MAX:d.plusDays(1).atStartOfDay();}
    static Map<String,Object> toDto(Object[]r){Map<String,Object>m=new LinkedHashMap<>();m.put("inventoryTransactionId",r[0]);m.put("inventoryItemId",r[1]);m.put("orderId",r[2]);m.put("transactionType",r[3]);m.put("quantity",r[4]);m.put("quantityBefore",r[5]);m.put("quantityAfter",r[6]);m.put("referenceType",r[7]);m.put("referenceId",r[8]);m.put("reason",r[9]);m.put("note",r[10]);m.put("createdBy",r[11]);m.put("unitCostSnapshot",r[12]);m.put("totalCost",r[13]);m.put("goodsReceiptId",r[14]);m.put("stockCountId",r[15]);m.put("createdAt",r[16]);return m;}
    public Map<String,Object> find(Integer item,Integer order,String type,LocalDate fromDate,LocalDate toDate,int page,int size){LocalDateTime from=fromDate==null?null:fromDate.atStartOfDay(),to=toDate==null?null:toEnd(toDate);List<String>c=buildConditions(item,order,type,from,to);EntityManager em=DatabaseUtil.getEntityManager();try{String w=where(c);Query rows=em.createQuery("SELECT t.inventoryTransactionId,i.inventoryItemId,o.orderId,t.transactionType,t.quantity,t.quantityBefore,t.quantityAfter,t.referenceType,t.referenceId,t.reasonCode,t.note,u.userId,t.unitCostSnapshot,t.totalCost,g.goodsReceiptId,s.stockCountId,t.createdAt FROM InventoryTransaction t LEFT JOIN t.inventoryItem i LEFT JOIN t.order o LEFT JOIN t.createdBy u LEFT JOIN t.goodsReceipt g LEFT JOIN t.stockCount s"+w+" ORDER BY t.createdAt DESC,t.inventoryTransactionId DESC",Object[].class),count=em.createQuery("SELECT COUNT(t) FROM InventoryTransaction t"+w,Long.class);params(rows,c,item,order,type,from,to);params(count,c,item,order,type,from,to);List<?>raw=rows.setFirstResult(firstResult(page,size)).setMaxResults(size).getResultList();long total=(long)count.getSingleResult();List<Map<String,Object>>items=new ArrayList<>();for(Object r:raw)items.add(toDto((Object[])r));return Map.of("items",items,"page",page,"size",size,"totalItems",total,"totalPages",(int)((total+size-1)/size));}finally{em.close();}}
    private static void params(Query q,List<String>c,Integer item,Integer order,String type,LocalDateTime from,LocalDateTime to){if(c.contains("t.inventoryItem.inventoryItemId = :inventoryItemId"))q.setParameter("inventoryItemId",item);if(c.contains("t.order.orderId = :orderId"))q.setParameter("orderId",order);if(c.contains("t.transactionType = :transactionType"))q.setParameter("transactionType",type);if(c.contains("t.createdAt >= :fromDate"))q.setParameter("fromDate",from);if(c.contains("t.createdAt < :toDate"))q.setParameter("toDate",to);}
}
