import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const page=readFileSync(new URL('../src/views/admin/AttendancePage.vue',import.meta.url),'utf8');
const api=readFileSync(new URL('../src/api/admin.js',import.meta.url),'utf8');
test('R6 exposes append-only pay rate history and creation',()=>{assert.match(api,/getStaffPayRates/);assert.match(api,/createStaffPayRate/);assert.match(page,/Mức công nhân viên/);assert.match(page,/effectiveFrom/);assert.match(page,/regularHourlyRate/);assert.match(page,/overtimeHourlyRate/);});
test('R6 renders snapshot preview missing and legacy states truthfully',()=>{for(const field of ['previewTotalPayAmount','totalPayAmount','paySnapshotStatus'])assert.match(page,new RegExp(field));assert.match(page,/Chưa cấu hình mức công/);assert.match(page,/Không có snapshot lịch sử/);assert.match(page,/Kết quả tháng/);assert.doesNotMatch(page,/Bảng lương|Thuế|Bảo hiểm/);});
test('R6 blocks approval without an effective rate',()=>{assert.match(page,/:disabled="[^"]*effectiveRegularHourlyRate/);});
test('attendance and pay rates are separate accessible modes',()=>{assert.match(page,/const attendanceView = ref\('attendance'\)/);assert.match(page,/role="tablist"/);assert.match(page,/Duyệt chấm công/);assert.match(page,/Mức tiền công/);assert.match(page,/aria-selected/);});
test('attendance pay truth labels cannot be confused',()=>{for(const label of ['Đã tính theo snapshot','Dự kiến','Chưa cấu hình mức công','Không có snapshot lịch sử'])assert.match(page,new RegExp(label));assert.match(page,/attendanceStatus === 'APPROVED'/);assert.match(page,/expectedUpdatedAt/);});
